[WIP] Add paste image
forem/forem pull request #10212
Opened 2020-09-04 19:37 UTC by Link2Twenty

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Add ability to paste images along side drag and drop

## Related Tickets & Documents
closes #10210

## QA Instructions, Screenshots, Recordings

1. Copy an image into your clipboard.
2. Paste it into article body
3. See it appear

## Added tests?

- [ ] yes
- [ ] no, because they aren't needed
- [x] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

## [optional] Are there any post deployment tasks we need to perform?
N/A

## [optional] What gif best describes this PR or how it makes you feel?

![Mad Scientist](https://thumbs.gfycat.com/CluelessSeveralAoudad-size_restricted.gif)

2020-10-08 11:55 UTC, Link2Twenty commented
@nickytonline I think this is ready now, sorry it took a while 😅

2020-10-08 15:55 UTC, MarcelloTheArcane commented
DO IT DO IT DO IT! 🎉

2021-01-26 12:11 UTC, ludwiczakpawel approved these changes
I've merged the latest `master` (even though my commits history is a bit weird..?). It works perfect! Great job! I apologize it slipped out of our attention :C

2021-01-26 17:56 UTC, katiedavis approved these changes
Great!

2021-01-26 18:45 UTC, nickytonline requested changes
This looks great @Link2Twenty. One small request change. Looking forward to see this in action!

2021-01-26 18:45 UTC, nickytonline commented on app/javascript/utilities/pasteImage.js
> +}
Refactor (blocking): We're only returning a setter function. There is no need to return it in an object.

```suggestion
export function usePasteImage({ onPaste }) {
  const [element, setElement] = useState(null);

  useEffect(() => {
    if (!element) return;

    element.addEventListener('paste', onPaste);

    return () => {
      element.removeEventListener('paste', onPaste);
    };
  }, [element, onPaste]);

  return setElement;
}
```

2021-01-26 18:45 UTC, nickytonline commented on app/javascript/article-form/components/EditorBody.jsx
> +  }).setElement;
Refactor (blocking): Ties into my refactor below.

```suggestion
  const setPasteElement = usePasteImage({
    onPaste: handleImagePasted(
      handleImageSuccess(textAreaRef),
      handleImageFailure,
    )
  });
```

2021-01-26 18:59 UTC, nickytonline requested changes
@Link2Twenty I was testing this in Firefox and it throws an error. I believe we just need to check if the name property exists or not and if it doesn't just give it a default name like `"image"`.

![image](https://user-images.githubusercontent.com/833231/105891016-1c78f680-5fde-11eb-8eb6-7a9b580f35d1.png)

2021-01-28 16:53 UTC, nickytonline commented
@Link2Twenty, I've merged the latest from the main branch. Please grab latest of your branch. Thanks!

2021-01-28 17:08 UTC, Link2Twenty commented
I've been having issues with gitpod which have prevented me from being able to work out the firefox issue.

2021-01-28 17:32 UTC, nickytonline commented
One of the folks on the front-end team can take a peek at the Firefox issue if you want. It should be a pretty simple check to add an image name if there is none. cc: @forem/frontend

2021-02-02 10:26 UTC, aitchiss commented
@Link2Twenty @nickytonline I've added a small change to work around the firefox issue - if the file detail array is empty we now add "alt text" as the alt, matching what we auto-populate through the manual image upload :)

2021-02-02 15:27 UTC, nickytonline approved these changes
Andrew, @aitchiss made the fix for Firefox, so this is good to go.

Thanks for the PR @Link2Twenty! 🚢

2021-02-02 15:33 UTC, nickytonline requested changes
Oops, looks like we need some tests here. @Link2Twenty, do you still need help with the testing?

2021-02-03 16:26 UTC, aitchiss commented
@Link2Twenty @nickytonline I've added some tests for the hook itself and one of the helper functions. The other `handleImagePasted` helper function relies on the paste event - we could create a mock/fake event but I'm not sure we'd get much value from testing it that way (since we'd just be validating against our own assumptions of what that event should look like). Let me know if you disagree / can see another way though 🙂

2021-02-04 15:58 UTC, nickytonline approved these changes
Thanks so much for the PR @Link2Twenty and thanks @aitchiss forthe tests! 👏🏻🔥

2021-02-04 15:58 UTC, merged