Add image composite element to feed if user exists
forem/forem pull request #10739
Opened 2020-10-08 16:00 UTC by jonathanyeong

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Renders an `<image>` tag in the RSS feed. If the feed is a tag or the latest feed, user won't exist and we will omit this field.

## Related Tickets & Documents

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added tests?

- [ ] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [ ] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2020-10-08 16:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/forem/forem?pullRequest=10739) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/forem/forem?pullRequest=10739) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/forem/forem?pullRequest=10739) it.</sub>

2020-10-08 16:01 UTC, jonathanyeong commented
Totally taking a stab in the dark. Draft PR for now - I'm still trying to get everything setup locally 😃.

2020-10-14 15:33 UTC, jonathanyeong commented
@rhymes what are thoughts on the rubocop block length error? Should we disable block length for the `feed.rss.builder`? I could use partials, but I read on SO that there's issues with identing: https://stackoverflow.com/questions/2986245/ruby-on-rails-using-xml-builder-partials.

2020-11-05 13:50 UTC, rhymes requested changes
Hi @jonathanyeong, thanks for tackling this, sorry for the late reply! 

I think we should add a few tests, based on my notes here https://github.com/forem/forem/issues/9934#issuecomment-703224961

2020-11-05 13:50 UTC, rhymes commented on app/views/articles/feed.rss.builder
> +        xml.title user.name
This should probably be `#{user.username} profile image`

2020-11-11 05:18 UTC, jonathanyeong commented
Gotcha makes sense! Having a look at moving it into a partial. Hopefully, dealing with the indentation isn't terrible!

2020-12-17 11:36 UTC, rhymes approved these changes
Hi @jonathanyeong! 

I manually tested the code and ran the tests locally and all works great. The build is temporarily having issue that will be resolved soon.

In the meantime I went ahead and approved :D

2020-12-17 15:10 UTC, jonathanyeong commented
@rhymes woohoo thank you so much! This is my first forem pr!

2020-12-17 15:42 UTC, rhymes commented
@jonathanyeong welcome to the project :))

2020-12-17 17:25 UTC, juliannatetreault approved these changes
Thanks so much for taking the time to contribute to Forem, @jonathanyeong! I tested your PR locally and everything works as expected! I also really appreciate the tests that you added around your changes--this is great. 🎉

2020-12-17 17:27 UTC, merged