fix bug on chat input
forem/forem pull request #10755
Opened 2020-10-09 16:58 UTC by narender2031

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
- In connect input. When user press `shift`+ `enter`. it was clearing the text input. 

## Related Tickets & Documents

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2020-10-10 06:28 UTC, narender2031 commented
@nickytonline Please restart the build

2020-10-14 06:46 UTC, narender2031 commented
any updates on this @citizen428 ?

2020-10-14 10:17 UTC, nickytonline requested changes
tests (blocking): Add some tests for this change.

2020-10-16 10:20 UTC, narender2031 commented
> tests (blocking): Add some tests for this change.
@nickytonline 
done

2020-10-19 01:18 UTC, citizen428 approved these changes

2020-10-19 01:18 UTC, citizen428 commented on app/javascript/chat/__tests__/compose.test.jsx
> +    it('should pressed enter and shift', () => {
**nitpick (non-blocking):** I think this message could be worded a bit differently, but we can do that later.

2020-10-19 01:56 UTC, nickytonline approved these changes

2020-10-19 01:57 UTC, nickytonline commented
Thanks for the PR @narender2031 and thanks for updating the tests.

2020-10-19 01:58 UTC, merged