SVG logo image re-sizing
forem/forem pull request #10826
Opened 2020-10-13 11:44 UTC by Ridhwana

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents
https://github.com/forem/InternalProjectPlanning/issues/53

## QA Instructions, Screenshots, Recordings

1. Go to http://localhost:3000/admin/config
2. Look for the logo svg
3. Upload any huge or small svg logo (with or without) heights set and it should resize appropriately to fit in the header.
4. In addition, you will see the resized logo being displayed in the config as well. 

**Here are some existing logos that weren't working that now resize properly:**
<img width="623" alt="Screenshot 2020-10-13 at 13 31 35" src="https://user-images.githubusercontent.com/2786819/95856087-c303f900-0d59-11eb-9234-14fca7e7f35d.png">
<img width="995" alt="Screenshot 2020-10-13 at 13 10 36" src="https://user-images.githubusercontent.com/2786819/95856103-c7c8ad00-0d59-11eb-8839-faba6750954d.png">

**Here is a random 48x48 width svg that I've uploaded:**
<img width="662" alt="Screenshot 2020-10-13 at 13 36 11" src="https://user-images.githubusercontent.com/2786819/95856045-b41d4680-0d59-11eb-9e2c-6c6175b63c70.png">

**Here are some existing logos that are still working with the fix:**
<img width="1133" alt="Screenshot 2020-10-13 at 13 39 54" src="https://user-images.githubusercontent.com/2786819/95855980-9cde5900-0d59-11eb-9796-6e088ce716a6.png">

<img width="846" alt="Screenshot 2020-10-13 at 13 32 17" src="https://user-images.githubusercontent.com/2786819/95856060-ba132780-0d59-11eb-9e8a-fd62c85dae86.png">

**Here is the config page that shows the resized logo as it would be displayed on the header:**
<img width="977" alt="Screenshot 2020-10-13 at 13 42 44" src="https://user-images.githubusercontent.com/2786819/95856292-17a77400-0d5a-11eb-9c25-dc824cc3e6fc.png">

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](https://media.giphy.com/media/rhfxbPtm4m5uo/giphy.gif)

2020-10-13 13:39 UTC, ludwiczakpawel approved these changes

2020-10-13 13:43 UTC, ludwiczakpawel requested changes
Oh wait, I've just realized we do have logos being used in more places and each of them have its own styling applied..

Check out the footer and `/new` page.

2020-10-13 15:21 UTC, rhymes approved these changes

2020-10-13 15:41 UTC, merged

2020-11-09 15:32 UTC, ludwiczakpawel commented
^ this should no longer be an issue, hopefully...