Refactoring suggested users
forem/forem pull request #10887
Opened 2020-10-17 03:38 UTC by Rafi993

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

Refactoring https://github.com/forem/forem/blob/master/app/javascript/sidebar-widget/SidebarWidget.jsx into functional component and simplifying the code

## Related Tickets & Documents
N/A

## QA Instructions, Screenshots, Recordings
1. Go to url http://localhost:3000/t/discuss
2. Scroll down to see suggested users on the right panel

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

2020-12-30 18:01 UTC, msarit commented
Hi @Rafi993! 👋🏾  Thanks for this PR. Think you could resolve the conflicts? Thanks so much.

2020-12-31 03:16 UTC, Rafi993 commented
> Hi @Rafi993! 👋🏾 Thanks for this PR. Think you could resolve the conflicts? Thanks so much.

I have fixed the merge conflicts now.

2021-01-07 05:03 UTC, nickytonline requested changes
Thanks for the PR Rafi! Just some change requests.

2021-01-07 05:38 UTC, nickytonline requested changes
Just another small change request.

2021-01-07 05:38 UTC, nickytonline commented on app/javascript/sidebar-widget/SidebarWidget.jsx
> +      ) || {};
Refactor (blocking): Setting a default value here does not seem necessary. We are always expecting `tagInfo` to be an object. If it isn't, Honeybader catches the unexpected error and reports it.

If we give it a a default value of `{}`, a valid request will be made that returns an empty array for the tag `undefined`.

2021-01-07 05:38 UTC, nickytonline commented on app/javascript/sidebar-widget/SidebarWidget.jsx
> +      const followBtn = document.getElementById(
Refactor (blocking): Using `useCallback` here and elsewhere in the PR seems like a premature optimization and it comes at a cost. See [When to useMemo and useCallback](https://kentcdodds.com/blog/usememo-and-usecallback).

2021-01-22 09:54 UTC, aitchiss requested changes
Looking good! Just one small change request 👍

2021-01-22 09:54 UTC, aitchiss commented on app/javascript/sidebar-widget/sidebarUser.jsx
> +  }, [followUser, user]);
Refactor (blocking): I think in this case we don't want to employ `useCallback` as we won't get any performance boost from it ([Kent C Dodds has a great article about this](https://kentcdodds.com/blog/usememo-and-usecallback)) - instead we can keep it simple with `const onClick = () => followUser(user)`

2021-01-22 16:04 UTC, aitchiss approved these changes
LGTM - left one minor/nitpicky suggestion for you to take or leave 🙂

2021-01-22 17:03 UTC, nickytonline approved these changes
Rafi, looks good to me as well. Just the nitpick about the `index` prop as well like @aitchiss mentioned. I don't see it being used either.

2021-02-03 17:47 UTC, merged

2021-02-03 17:48 UTC, aitchiss commented
Thanks for this one @Rafi993! ✨