Refactoring EditorAction
forem/forem pull request #10894
Opened 2020-10-18 03:25 UTC by Rafi993

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

Refactoring editor actions
  1. Removing nested ternary operators for improving readability
  2. Converting class component to functional component

## Related Tickets & Documents
 N/A

## QA Instructions, Screenshots, Recordings

1. Create a post and publish it
2. Edit a post
3. Convert a post to draft
4. Create a new post and save it as a draft

## Added tests?

- [ ] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

2020-10-28 07:31 UTC, Rafi993 commented
I think the code climate error might be a false positive.

2020-10-28 16:27 UTC, nickytonline requested changes
Looking good @Rafi993. A small change request.

2020-10-28 16:27 UTC, nickytonline commented on app/javascript/article-form/components/EditorActions.jsx
> +  const toggleMoreConfig = useCallback(
refactor (blocking): `useCallback` seems overkill here. For context, see  [When to useMemo and useCallback](https://kentcdodds.com/blog/usememo-and-usecallback).

2020-10-28 16:27 UTC, nickytonline commented on app/javascript/article-form/components/EditorActions.jsx
> +  const v1 = version === 'v1';
nitpick (non-blocking): consider naming these `isVersion1` and `isVersion2`.

2020-10-28 17:44 UTC, nickytonline approved these changes
Tested this locally and it LGTM. 🚀

2020-10-29 01:28 UTC, Rafi993 commented
> Tested this locally and it LGTM. 🚀

Thank you @nickytonline

2020-10-29 08:06 UTC, rhymes approved these changes

2020-10-29 08:06 UTC, merged