Add mailer previews for Devise mailer
forem/forem pull request #10890
Opened 2020-10-17 15:29 UTC by boardfish

Submitting in draft until I've tested this locally. Still haven't yet brought up my environment.

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Adds mailer previews for all Devise and DeviseInvitable mail.

## Related Tickets & Documents

#10575 

## QA Instructions, Screenshots, Recordings

View the mailer previews at http://localhost:3000/rails/mailers/devise_mailer.

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed - already present under Previewing Emails.

2020-10-21 01:23 UTC, benhalpern approved these changes

2020-10-21 01:23 UTC, benhalpern commented
This is great

2020-10-21 09:13 UTC, rhymes requested changes
Hi @boardfish ! This is not working for me, it says:

```ruby
Zeitwerk::NameError - expected file /forem/spec/mailers/previews/devise_mailer_preview.rb to define constant DeviseMailerPreview, but didn't:
   app/middlewares/set_cookie_domain.rb:13:in `call'
```

I think the issue here is in the nameing of the file. If the class is `Devise::MailerPreview` it should be located in `app/mailers/previews/devise/mailer_preview.rb` not `spec/mailers/previews/devise_mailer_preview.rb`

2020-10-21 09:20 UTC, boardfish commented
Thanks both for checking this out for me! I still haven't been able to get this running locally, but that makes sense @rhymes - I'd hope it ought to work once it's moved.

2020-10-26 14:46 UTC, rhymes reviewed
Hi @boardfish, some of these previews aren't working. As I remember you're having difficulties setting up the app, would you mind if I added the changes to make them work as I can test them locally?

2020-10-26 14:46 UTC, rhymes commented on spec/mailers/previews/devise/mailer_preview.rb
> +      Devise::Mailer.email_changed(User.last, User.last.email)
this is not working: http://localhost:3000/rails/mailers/devise/mailer/email_changed

2020-10-26 14:46 UTC, rhymes commented on spec/mailers/previews/devise/mailer_preview.rb
> +      Devise::Mailer.email_changed(User.last, "faketoken")
this is not working http://localhost:3000/rails/mailers/devise/mailer/invitation_instructions

2020-10-26 14:46 UTC, rhymes commented on spec/mailers/previews/devise/mailer_preview.rb
> +      Devise::Mailer.email_changed(User.last, "faketoken")
this is not working http://localhost:3000/rails/mailers/devise/mailer/reset_password_instructions

2020-10-26 14:56 UTC, boardfish commented
That'd be a quicker way to push this through for sure. Much appreciated!

2020-10-31 16:23 UTC, boardfish commented
Thanks for fixing those up @rhymes! Looking back, I made some big oversights, so I apologize for that.

Could this be labelled `hacktoberfest-accepted` if not merged, please?

2020-11-02 08:09 UTC, rhymes approved these changes

2020-11-02 08:10 UTC, merged