Spec Fix:Ensure Datetime is a String to Be Properly Parsed by local Date Helper
forem/forem pull request #11025
Opened 2020-10-22 18:49 UTC by mstruve

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added tests?

- [ ] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [ ] no documentation needed

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2020-10-22 23:47 UTC, mstruve commented on app/assets/javascripts/base.js.erb
> +<% if Rails.env.test? %>
I'm sure there is a much better place to put this. @vaidehijoshi or @nickytonline please feel free to jump in, I am not very familiar with our js organization.

2020-10-23 10:00 UTC, rhymes requested changes
Awesome! Out loud makes perfect sense that the frontend and the backend are aligned in tests, on the other end though I wonder if this it's going to hide future issues. After all in production Forem servers run on UTC, clients don't. Do you think that could be an issue. We could probably catch those in a future CI pipeline where we run some builds in UTC and some in the random zonebie provided time zone. This also might not be needed if we eventually move away from Rails system tests and use end to end testing where I'm sure we can simulate whatever time zone we want.

Anyhow:

I'm not sure what's the best place either for the time machine initializer but it seems a good one! :D 

Great find for https://makandracards.com/makandra/10753-mock-the-browser-time-or-time-zone-in-selenium-features - we should add it to our knowledge base ehheh.

I requested changes because the library shoulnd't be packaged in production

2020-10-23 12:23 UTC, mstruve commented on package.json
> +    "timemachine": "^0.3.2",
Ah, thank you! I didnt realize you could do that like gems!

2020-10-23 15:15 UTC, vaidehijoshi approved these changes
This is great! Agree with @rhymes on where to include in dependencies 👍

2020-10-23 15:15 UTC, vaidehijoshi commented on app/assets/javascripts/initializers/initializeTimemachine.js.erb
> +  // Ensure that locale time in javascript matches the Timezone on
```suggestion
  // Ensure that locale time in JavaScript matches the Timezone on
```
😉

2020-10-23 16:27 UTC, mstruve commented on app/assets/javascripts/initializers/initializeTimemachine.js.erb
> +  // Ensure that locale time in javascript matches the Timezone on
You are like me and Elasticsearch 😅

2020-10-26 10:10 UTC, rhymes approved these changes

2020-10-26 12:51 UTC, merged