new liquid -> emgithub
forem/forem pull request #11280
Opened 2020-11-05 04:42 UTC by ShubhankarKG

## What type of PR is this? (check all applicable)

- [x] Feature

## Description
This is a preliminary support for emgithub tag, there's a slight bit of problem and I think it best to have a discussion on this before proceeding further.

## Related Tickets & Documents
Fixes #10151 

## QA Instructions, Screenshots, Recordings

1. Add a new post with the liquid tag **emgithub** and the Github link. for eg: 
```liquid
{% emgithub https://github.com/CommunityOfCoders/COCWebsite/blob/master/new_client/package.json#L2-L7 %}
```
![Screenshot from 2020-11-05 09-59-15](https://user-images.githubusercontent.com/50791000/98198597-4c6cac80-1f4f-11eb-9d85-e9311bdf939f.png)

2. Go to preview tab.
![Screenshot from 2020-11-05 09-59-25](https://user-images.githubusercontent.com/50791000/98198609-568eab00-1f4f-11eb-9a9d-db2c8e00a72a.png)

3. Publish post and see result.
![Screenshot from 2020-11-05 09-59-48](https://user-images.githubusercontent.com/50791000/98198629-64443080-1f4f-11eb-9070-6a4585409641.png)

## Added tests?

- [x] No, and this is why: Will write once the flow gets finalized.

## Added to documentation?
- [ ] Docs.forem.com
- [ ] README
- [ ] No documentation needed

2020-11-05 14:22 UTC, rhymes requested changes
Hi @ShubhankarKG, thanks for kickstarting this. I left a bunch of notes inline, in addition we should definitely take care of the following things:

- preview is not working, as this is a script and not an iframe, the script should be ran dynamically, see https://github.com/forem/forem/blob/7a6ad7b83ab223e980479709e69dc35eb4b1f4d6/app/views/articles/show.html.erb#L238-L248 and https://github.com/forem/forem/blob/7a6ad7b83ab223e980479709e69dc35eb4b1f4d6/app/views/comments/index.html.erb#L133-L139 for how that is done (plus the correspondent tags)
- tests are missing
- we need CSS to limit the vertical length of the container div, otherwise it can be very very long, see the screenshot:

![Screenshot_2020-11-05 test emgithub](https://user-images.githubusercontent.com/146201/98252890-b8b0d580-1f7a-11eb-8bf8-3140cd16d5de.png)

ps. don't forget to prefix the branch with your username the next time, see the [contributing guide](https://docs.forem.com/contributing/forem/)

2020-11-05 14:22 UTC, rhymes commented on app/liquid_tags/emgithub_tag.rb
> +  LINK_REGEXP = %r{\A(http|https)://github.com/[a-zA-Z0-9]*/[a-zA-Z0-9]*/blob/[a-zA-Z0-9_./#-]*\z}.freeze
Mmm this regexp would also match something like `https://github.com///blob/`

It's probably easier to just check if the URL starts with github.com, it's followed by `/\w+/\w+/blob/` and the optional chars you put at the end. Remember that `*` means 0 ore more, we need at least 1 per each part of the path. You can test on https://rubular.com/

2020-11-05 14:22 UTC, rhymes commented on app/liquid_tags/emgithub_tag.rb
> +    raise StandardError, "Invalid Github URL" unless valid_link?(the_link)
this should be `GitHub`

2020-11-13 08:11 UTC, ShubhankarKG commented
![Screenshot from 2020-11-13 13-37-27](https://user-images.githubusercontent.com/50791000/99044454-cb985b00-25b5-11eb-8c77-4336f7520f43.png)
![Screenshot from 2020-11-13 13-37-18](https://user-images.githubusercontent.com/50791000/99044458-ccc98800-25b5-11eb-8e08-9ed893ce4036.png)

Update after this commit, that is. Will work on the CSS as and tests as well

2020-11-13 12:05 UTC, ShubhankarKG commented
If there is a view more button, what should it show? View on GitHub? because running the script will load the entire set if lines aren't provided or the line diff set is huge.

2020-11-18 06:50 UTC, ShubhankarKG commented
I'm having some difficulty in setting up this max height thing. Can someone give some pointers please :sweat_smile:? Perhaps a PR that also faced this difficulty would also work. Thanks :pray:

2020-12-30 18:14 UTC, msarit commented
Hi @ShubhankarKG! 👋🏾 

I'm returning this PR to draft status, since certain aspects are still being worked out. Please feel free to un-draft it once it is ready! Thanks! 🙏🏾

2021-01-04 16:54 UTC, nickytonline requested changes
@ShubhankarKG, just doing a first pass even though this is in draft.

2021-01-04 16:54 UTC, nickytonline commented on app/javascript/article-form/articleForm.jsx
> +  static handleEmgithubPreview() {
refactor (blocking): The article form's purpose it to edit a post. It has no knowledge of liquid tags. Take a peek at existing liquid tags, like this one https://github.com/forem/forem/blob/d9011f4b593469d60499900660818e8ee897c382/app/liquid_tags/user_subscription_tag.rb

2021-01-06 05:04 UTC, ShubhankarKG commented
Hey everyone, sorry to be saying this but at this moment, I won't be able to continue on this PR :disappointed: I apologize, but I have serious time constraints and so, cannot complete this. I appreciate the help! But again, I apologize.

2021-01-06 05:05 UTC, ShubhankarKG commented
Thanks everyone! I look forward to contributing some time in the future!

2021-01-06 05:05 UTC, closed without merging

2021-01-06 14:59 UTC, nickytonline commented
No problem @ShubhankarKG. Looking forward to your future contributions!