Fixed the scroll bar problem in Safari
forem/forem pull request #11387
Opened 2020-11-12 12:50 UTC by damla

- 👷‍♀️ Create small PRs. In most cases this will be possible.
     - ✅ Provide tests for your changes.
     - 📝 Use descriptive commit messages.
     - 📗 Update any related documentation and include any relevant screenshots.

## What type of PR is this?

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

As you guys know, while editing a new post, there is a modal box used for demonstrating markdown formats and liquid tags. In Safari, I realized that the scroll bar is overflowing at the bottom of the modal as shown in Screenshot no.1. So, adding "overflow: hidden;" to the class of that modal, which is "crayons-modal__box", fixed the problem. 

I've also checked it on Firefox and Google Chrome and they do not have any bug like this.(Screenshot no.2 and Screenshot no.3)

## Related Tickets & Documents

**Folder location:** `forem/app/assets/stylesheets/components/modal.scss`

## QA Instructions, Screenshots, Recordings

  <img width="1440" alt="safari" src="https://user-images.githubusercontent.com/24878421/98940387-f45c1a00-24fb-11eb-891d-0338eb8c8f9f.png">
<p align="center">Screenshot no.1 - Problem in Safari</p>

<img width="1440" alt="firefox" src="https://user-images.githubusercontent.com/24878421/98941134-2b7efb00-24fd-11eb-941d-dfe7167fbca4.png">
<p align="center">Screenshot no.2 - Firefox</p>

<img width="1440" alt="google_chrome" src="https://user-images.githubusercontent.com/24878421/98941194-418cbb80-24fd-11eb-8cae-828f1abb6b7a.png">
<p align="center">Screenshot no.3 - Google Chrome</p>

_You may test the changes by entering to "write a new post page" and clicking on Markdown or Liquid Tags link found in the right section._

## Added tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [x] I need help with writing tests

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [x] No documentation needed

## What gif best describes this PR or how it makes you feel?

![like a cat](https://media.giphy.com/media/BzyTuYCmvSORqs1ABM/giphy.gif)

2020-11-12 12:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/forem/forem?pullRequest=11387) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/forem/forem?pullRequest=11387) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/forem/forem?pullRequest=11387) it.</sub>

2020-11-12 14:02 UTC, rhymes commented
Hi @damla, I wonder if this only applies to some versions of Safari because I'm not experiencing the issue. I tried with `Version 14.0 (15610.1.28.1.9, 15610)`

2020-11-12 14:27 UTC, damla commented
Hi @rhymes, I checked my version and it is `Version 14.0 (15610.1.28.1.9, 15610)` too. Then, I tried the same scenario with a long post (scrollable) and empty post. It seems like when the post is scrollable, modal with markdown does not having this problem but liquid tag does. I screen recorded it to demonstrate it better.
![test1](https://user-images.githubusercontent.com/24878421/98951718-a94a0300-250b-11eb-9d74-ff259ad274ca.gif)
I converted it to a gif so, it is a little bit slow 😕

2020-11-12 14:37 UTC, rhymes commented
Thanks! I wonder if it's a question of resolution or I haven't fully understood where the defect lies :D 

This is from my Safari:

![modal](https://user-images.githubusercontent.com/146201/98953347-de028e00-24fc-11eb-8438-307b198cd1f4.gif)

2020-11-12 15:13 UTC, damla commented
I updated my macOS version to` 10.15.7` to be sure, but it still has the same problem. My screen size is 13 inch btw, maybe it can be helpful.

2020-11-12 16:36 UTC, damla commented
Hi @rhymes, I just realized when I disconnect my mouse and just use the trackpad, the scroll bar become hidden as default. Here is a screenshot of it:
<img width="791" alt="image" src="https://user-images.githubusercontent.com/24878421/98966231-16659480-251c-11eb-8366-7970524f75b9.png">

But when I plugged in the dongle, scroll bar is always there like shown in this screenshot:
<img width="797" alt="image" src="https://user-images.githubusercontent.com/24878421/98967862-077fe180-251e-11eb-8b38-76e5a3a34f80.png">

After I added "overflow:hidden;" from dev tools in Safari, it becomes like this:
<img width="849" alt="image" src="https://user-images.githubusercontent.com/24878421/98968056-43b34200-251e-11eb-97ac-2e8af45e8e25.png">

2020-11-16 10:50 UTC, ludwiczakpawel commented
I believe the issue that @damla is talking about is the scenario when you can notice ~1px of the scrollbar being on top of the that black shadow, is that correct?

If yes, I think I know what the cause of this issue, and it's actually pretty funny bug (well, in a way :))

On Safari, when you have smaller window resolution (height in particular), the modal header gets shrinked (see how squeezed it is on screenshot? This behavior is kinda correct and it's quite funny how browser handle shrinking elements like that ("like that" = part of flexbox). So browser doesn't shrink this element with whole pixels (50px, 49px, 48px...) but with decimal fractions which could be anything like (50px, 49.999px, 49.998px, ...). The actual values for fractions are dependent on window size and the layout of particular elements (in our case: modal header + modal body). 

Now the fun part is that even if one element (modal header) has height with values with decimal fractions, the other element (modal body) doesn't really care and tries to use rounded numbers.

That's why you can *sometimes* spot that scrollbar being on top of the shadow - and it's not really `1px` - it can be anything between `0px` and `1px` :).

And fix for this is actually quite simple: we have to add `flex-shrink: 0;` to [`.modal__header` element](https://github.com/forem/forem/blob/master/app/assets/stylesheets/components/modals.scss#L72) - that should do the trick :)

---

PS. It was really fun to debug this :)

2020-11-16 10:55 UTC, ludwiczakpawel requested changes
^

2020-11-16 11:22 UTC, ludwiczakpawel approved these changes
⛴ Ship it! ⛴

2020-11-16 11:23 UTC, damla commented
Hi @ludwiczakpawel, thanks for explaining the bug in detail, I've learned a lot from it 🙃

2020-11-16 11:48 UTC, rhymes approved these changes

2020-11-16 11:48 UTC, merged