Added additional tags to allow in sanitization while parsing details tag content
forem/forem pull request #11413
Opened 2020-11-15 05:17 UTC by akashdotsrivastava

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [ ] No documentation needed

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2020-11-15 06:58 UTC, rhymes requested changes
Hi @akashdotsrivastava, thanks for the changes!

A couple of things: I think we can use 

```ruby
Rails::Html::SafeListSanitizer.allowed_tags + ["iframe"]
```

same for the attributes. This way we don't have to duplicate the default allowed tags list.

Regarding allowing the iframe, could you add a few test cases? I suspect this change will work not only with YouTube but any of the other liquid tags that renders as an `<iframe>`

I tried with `codesandbox` and it worked:

![Screenshot_2020-11-15 details + codesandbox](https://user-images.githubusercontent.com/146201/99178900-4f6a5880-2718-11eb-83d2-853326d556e1.png)


1. it'd be nice to preserve the previous simple case for `<details>`
1. it'd be nice to add this case with the iframe separately
1. finally it'd be nice if we had a separate test case, maybe beside this https://github.com/forem/forem/blob/910f79e04e402214f33600cddb44367e9c6e5d45/spec/system/articles/user_creates_an_article_spec.rb#L16 that checks that one of the other combo of `<details>` + embedded liquid tag works (one is sufficient, it's more of a regression test). 

What do you think?

2020-11-15 09:53 UTC, akashdotsrivastava commented
> What do you think?

@rhymes Thanks for the feedback. All of it makes sense. Changes done.

2020-11-15 10:26 UTC, rhymes approved these changes
Awesome, thanks @akshayymahajan!

2020-11-15 10:28 UTC, akshayymahajan commented
@rhymes, I think you wanted to tag @akashdotsrivastava 😃

2020-11-15 10:33 UTC, rhymes commented
@akashdotsrivastava @akshayymahajan sorry :-(

2020-11-18 15:14 UTC, msarit approved these changes
Great work, @akashdotsrivastava! Thanks for contributing!

2020-11-18 15:46 UTC, rhymes commented
Setting this back to draft temporarily to avoid accendital merges as we want to review it from a security perspective, thank you for the patience @akashdotsrivastava

2020-12-29 18:52 UTC, msarit commented
@rhymes Hey Rhymes, pinging you re: ensuring security on this PR 🙏🏾

2021-03-01 03:48 UTC, citizen428 commented
@rhymes What are our next steps on this PR?

2021-03-01 10:17 UTC, rhymes commented
@citizen428 I think we should surface it to the team, as I'm not sure if it's safe to merge and I'd like feedback on the implementation and possible security considerations

2021-03-22 14:53 UTC, msarit commented
@rhymes @citizen428 Hey people! This PR needs to be discussed re: security concerns. 🙏🏾

2021-07-01 18:34 UTC, msarit commented
I pinged relevant players for this PR in [this issue](https://github.com/forem/security/issues/374)

2021-07-09 15:12 UTC, maestromac commented
Hey @akashdotsrivastava , thank you again for your time and contribution. Due to a combination of reasons, we can not proceed with this solution.

The problem is with our sequential parsing; We would parse markdown first then the liquid tag. If the content of this details liquid tag contains markdown, those will not be processed and remain as raw markdown. Manually allowing the iframe tag to get through would open up the possibility of XSS.

The proper path forward would be to add details and a summary tag to our `RenderedMarkdownScrubber` and eventually remove the details liquid tag. Using raw details and summary tags would eliminate the problem we're trying to solve in this PR and allow full markdown parsing within the details block.

You are more than welcome to open up another PR and address those concerns. Let me know and I am more than happy to provide you directions.

2021-07-09 15:12 UTC, closed without merging

2021-07-09 15:54 UTC, akashdotsrivastava commented
@maestromac Thanks for the update. 
I'll have a look and try to come up with a different PR using the route above in some time. I will update if I need help. Thanks again ♥️👍

2021-07-09 15:55 UTC, maestromac commented
@akashdotsrivastava . It's really a 1 line change + specs. You do not have to worry about removing Details liquid tag. I will do that since it requires a bit of planning and migration.