Adding podcast_ownership controller and pundit policy
forem/forem pull request #11557
Opened 2020-11-22 18:58 UTC by Manasa2850

What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Adding podcast_ownership controller and an associated pundit policy

## Related Tickets & Documents
This is an extension to https://github.com/forem/forem/pull/11410
Frontend / view for this controller will be worked on separately

## Added tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [x] No documentation needed

## [optional] Are there any post deployment tasks we need to perform?
No

2020-11-23 09:59 UTC, Manasa2850 commented
@rhymes could you please review this and let me know if the controller and pundit policy is fine? I can then start writing tests for them.

2020-11-23 10:46 UTC, rhymes commented
@Manasa2850 sure, they seem fine, I'll do a formal review when tests are added. Thank you!

2020-11-23 16:00 UTC, Manasa2850 commented
@rhymes I get an error with this statement `let(:user)       { build_stubbed(:owner) }` in the pundit policy tests. 
Could you please guide me regarding this?

2020-11-23 16:13 UTC, rhymes commented
@Manasa2850 `build`, `build_stubbed`, `create` factories require the name of the factory, see the `spec/factories` folder that have been registered. `owner` is the name of the virtual relation between a podcast and its user's owner, but what you need is to fabricate a `:user`

2020-11-23 18:29 UTC, Manasa2850 commented
@rhymes could you please review this? I've added the tests

2020-11-24 08:57 UTC, rhymes commented
@Manasa2850 you still have a failing test, please investigate. This is also missing request specs for controllers, see for example: https://github.com/forem/forem/tree/master/spec/requests

2020-11-27 05:26 UTC, Manasa2850 commented
@rhymes I had a doubt regarding the controller specs.
When I created the controller using `rails generate`, a default `podcast_ownerships_request_spec.rb` file was created. Should I write the specs here or create separate files for `create, destroy and update` functions in the `spec/requests/podcast` folder?

2020-11-27 15:43 UTC, rhymes commented
@Manasa2850 I think having `spec/requests/podcasts/podcast_ownerships_destroy_spec.rb` with all the specs for the various methods is best

2020-11-27 15:44 UTC, Manasa2850 commented
@rhymes I'm going to have 3 files
`spec/requests/podcasts/podcast_ownerships_destroy_spec.rb`
`spec/requests/podcasts/podcast_ownerships_create_spec.rb`
`spec/requests/podcasts/podcast_ownerships_update_spec.rb`

2020-11-27 15:46 UTC, rhymes commented
@Manasa2850 I think one file is good enough but as you wish :)

2020-11-27 19:31 UTC, Manasa2850 commented
@rhymes I just realized that we don't really have a use for the `update` method :sweat_smile: 
The only thing required is to add or delete a user as the owner of a podcast which can be achieved by the `create` and `destroy` methods.
What do you think about this?

2020-11-28 10:38 UTC, rhymes commented
@Manasa2850 I answered you here https://github.com/MLH-Fellowship/dev.to/issues/81#issuecomment-735215087

2020-12-08 14:34 UTC, mkcode commented on app/controllers/podcast_ownerships_controller.rb
> +      flash[:error] = "User is already an owner"
Use error object on podcast ownership. See: https://guides.rubyonrails.org/active_record_validations.html#valid-questionmark-and-invalid-questionmark

2020-12-08 14:36 UTC, mkcode requested changes
Address comments

2020-12-08 14:36 UTC, mkcode commented on app/controllers/admin/podcast_ownerships_controller.rb
> +  end
Move this to PodcastOwnershipsController where it is being called.

2020-12-08 14:36 UTC, mkcode commented on app/controllers/podcast_ownerships_controller.rb
> +  end
Nothing to update. Just create and destory.

2020-12-08 14:36 UTC, mkcode commented on app/controllers/podcast_ownerships_controller.rb
> +    if @podcast_ownership.save
Let's use the policy in the controller.

2020-12-08 14:36 UTC, mkcode commented on app/controllers/podcast_ownerships_controller.rb
> +    if @podcast_ownership.save
Via the `authorize` method.

2021-02-05 18:14 UTC, msarit commented
Hello @Manasa2850! 👋🏾 

Drawing your attention to this PR; looks like you have some feedback to incorporate.

Let me know if you have any questions or need help. 🙏🏾

2021-02-06 10:58 UTC, Manasa2850 commented
Hi @msarit. I was working on this feature as part of the MLH Fellowship. I'll not be able to continue working on this anytime soon. Please feel free to close this PR. 
Thank you!

2021-02-06 11:11 UTC, closed without merging