add crayons classes
forem/forem pull request #12346
Opened 2021-01-20 08:14 UTC by narender2031

## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
 refactor the UI for the delete my account page
## Related Tickets & Documents
#12296

## QA Instructions, Screenshots, Recordings

<img width="1440" alt="Screenshot 2021-01-20 at 11 35 18 AM" src="https://user-images.githubusercontent.com/25151772/105146046-85b3c200-5b25-11eb-895f-2bf37666aab6.png">

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://docs.forem.com/frontend/accessibility)._

## Added tests?

- [ ] Yes
- [x] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [x] No documentation needed

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2021-01-20 08:57 UTC, rhymes commented
@narender2031 I converted the branch to draft 👍

2021-01-25 09:23 UTC, narender2031 commented
@ludwiczakpawel any update on this PR?

2021-01-25 11:21 UTC, ludwiczakpawel requested changes
It's definitely a good start although I've suggested several code changes to make it look more readable and structured properly.

2021-01-25 11:21 UTC, ludwiczakpawel commented on app/views/users/confirm_destroy.html.erb
> +      <h4 class="fw-normal">
Let's drop this entire `h4` - if anything, it should be `div` but in this case i don't think we need another container here.

```suggestion
```

2021-01-25 11:21 UTC, ludwiczakpawel commented on app/views/users/confirm_destroy.html.erb
> +          <ul class="delete__account mb-4">
```suggestion
          <ul class="my-0 ml-6 list-disc">
```

^ dropping unnecessary class name and adding a bit of styling.

2021-01-25 11:21 UTC, ludwiczakpawel commented on app/views/users/confirm_destroy.html.erb
> +          </div>
```suggestion
        <div class="crayons-field m:w-50">
          <label for="delete__account__username__field" class="crayons-field__label">
            Type in your username
          </label>
          <input type="text" name="delete__account__username__field" class="crayons-textfield " id="delete__account__username__field" placeholder="username">
        </div>
        <div class="crayons-field m:w-50">
          <label for="delete__account__verification__field" class="crayons-field__label">
            For confirmaiton, type the words: <code>delete my account</code>
          </label>
          <input type="text" name="delete__account__verification__field" class="crayons-textfield" id="delete__account__verification__field">
        </div>
```

- this is how `.crayons-field` component should be used with pure HTML so it does render properly
- I've also suggested some changes to the copy as well.

2021-01-25 11:21 UTC, ludwiczakpawel commented on app/views/users/confirm_destroy.html.erb
> +        <%= form_tag user_full_delete_path, method: :delete, autocomplete: "off", id: "delete__account" do %>
```suggestion
        <%= form_tag user_full_delete_path, method: :delete, autocomplete: "off", id: "delete__account", class: 'flex flex-col gap-4 mb-4' do %>
```

`flex flex-col gap-4` will automatically apply spacing between its children elements.

2021-01-25 11:21 UTC, ludwiczakpawel commented on app/views/users/confirm_destroy.html.erb
> +          </ul>
```suggestion
          </ul>
          <h3>To delete your account:</h3>
```

This should structure everything slightly better.

2021-01-25 11:21 UTC, ludwiczakpawel commented on app/views/users/confirm_destroy.html.erb
> +      <br>
```suggestion
```

2021-01-25 11:21 UTC, ludwiczakpawel commented on app/views/users/confirm_destroy.html.erb
> +    <h2 class="crayons-title"> Destroy your account</h2>
```suggestion
    <h2 class="crayons-title mb-4"> Destroy your account</h2>
```

^ adding a bit of spacing below page title.

2021-01-25 19:25 UTC, narender2031 commented
@ludwiczakpawel can you please re-start the travis build again

2021-01-25 19:53 UTC, ludwiczakpawel commented
Oh it's actually properly failed. This `click_button` in spec is case-sensitive, so you may need to update this to "Delete account": https://github.com/forem/forem/blob/master/spec/system/user/user_self_destroy_spec.rb#L50

2021-01-26 11:39 UTC, ludwiczakpawel approved these changes
👍

2021-01-26 15:28 UTC, rhymes approved these changes

2021-01-26 15:28 UTC, merged