Updates ESLint rules to error on default imports
forem/forem pull request #12512
Opened 2021-02-01 14:55 UTC by katiedavis

## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description
Updates our eslint rules to error on default JS exports. This provides consistency when importing javascript across the app. 

## Related Tickets & Documents
See #12383 

## QA Instructions, Screenshots, Recordings
I did some manual sanity testing, but it would be great if someone could just quickly hop on this branch and check to make sure nothing is broken! It most likely isn't though. 

## Added tests?

- [ ] Yes
- [x] No, and this is why: This PR updates a lint rule and the accompanying violations.
- [ ] I need help with writing tests

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [x] No documentation needed

![dancing janitor](https://media.giphy.com/media/xThuWcUB3BESQVfNpm/giphy.gif)

2021-02-01 19:27 UTC, nickytonline reviewed
Looking through this and all seems good. I'm just going to pull it locally to take it for a test drive.

2021-02-01 19:29 UTC, katiedavis commented
@nickytonline for some reason eslint didn't catch a bunch of files: https://codeclimate.com/github/forem/forem/pull/12512
I'm going to add another commit

2021-02-01 21:29 UTC, katiedavis commented on app/javascript/chat/ChatChannelSettings/RequestedMembershipSection.jsx
> +  requestedMemberships: PropTypes.arrayOf(defaultMembershipPropType).isRequired,
I had to update the typo I couldn't handle it

2021-02-02 14:07 UTC, aitchiss approved these changes
LGTM - I had a quick manual check and couldn't see any issues. I love seeing all those default exports cleaned up 😄

2021-02-02 14:30 UTC, jacobherrington approved these changes
LGTM

:broom: :wastebasket:

2021-02-02 15:12 UTC, nickytonline requested changes
Not a request change, just a spot check.

@katiedavis, although this is an eslint rule update/code refactor, it's still quite a lot of files.

Mind taking the site for a spin with the devtools open to see if anything blows up including the admin section? I would guess no, but it'd be good to do a sanity check as we've only recently started adding e2e tests. I'll do the same.

Thanks!

2021-02-02 15:19 UTC, katiedavis commented
> Not a request change, just a spot check.
> 
> @katiedavis, although this is an eslint rule update/code refactor, it's still quite a lot of files.
> 
> Mind taking the site for a spin with the devtools open to see if anything blows up including the admin section? I would guess no, but it'd be good to do a sanity check as we've only recently started adding e2e tests. I'll do the same.
> 
> Thanks!

Yeah for sure! I've just run through everything again and it's looking good on my end.

2021-02-02 15:23 UTC, nickytonline approved these changes
> Yeah for sure! I've just run through everything again and it's looking good on my end.

@katiedavis, I did a sanity check as well and things seems to be behaving properly. 🚢

2021-02-02 15:24 UTC, merged