Danieltott/fix flex gap 12452
forem/forem pull request #12667
Opened 2021-02-11 18:51 UTC by danieltott

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Safari doesn't support the `gap` property on `flex` containers. This PR contains individual fixes for all of the occurrences of `display: flex` + `gap`

## Related Tickets & Documents

- #12452: `gap` doesn't work with `flex` on Safari 

## Detailed description of changes

description incoming - drafting now

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://docs.forem.com/frontend/accessibility)._

## Added tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2021-02-11 18:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/forem/forem?pullRequest=12667) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/forem/forem?pullRequest=12667) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/forem/forem?pullRequest=12667) it.</sub>

2021-02-12 15:55 UTC, aitchiss requested changes
Thanks for these changes - things are looking a lot neater in Safari! I just noticed one issue following the changes - in the admin section > authentication > email> disable, the modal that pops up now looks like this:

![gif showing large vertical spacing between paragraphs inside a modal](https://user-images.githubusercontent.com/20773163/107790331-90d7c780-6d4a-11eb-8a8d-489039cbf8c5.gif)

Hopefully a small tweak can address that then we're good to go 👍

2021-02-12 17:50 UTC, danieltott commented
@aitchiss are you saying that _isn't_ what you want? 😂 Will get that fixed up today!

2021-02-12 20:11 UTC, danieltott commented
@aitchiss ok - should be all set now!

2021-02-15 14:37 UTC, aitchiss requested changes
Sorry one last thing! It looks great on desktop now, but that same modal has changed a bit on mobile - here's the before:

![Screenshot of modal showing content aligned top without significant gaps](https://user-images.githubusercontent.com/20773163/107959166-f15d4380-6f9a-11eb-8748-6105bf7a36b8.png)

and here's the after:

![Screenshot of the same modal, but the content is being distributed across the whole screen height](https://user-images.githubusercontent.com/20773163/107959186-f7532480-6f9a-11eb-9af0-1d3b7e2bb018.png)

I'm assuming it's because we show modals full screen on mobile devices, and the grid is just expanding to fill all of it 🤔

2021-02-15 20:16 UTC, danieltott commented
@aitchiss sorry, I'm not sure how I missed that - I swear I had it open in that view in Safari. _ANYWAY_, that is all fixed again and should be in good shape now.

2021-02-16 09:27 UTC, aitchiss approved these changes
Looks good to me! Thanks for making those tweaks - it's awesome to get all these bits refactored and neatened up 🙌

2021-02-16 13:24 UTC, ludwiczakpawel approved these changes
Nice! And only 20 files - I thought it's gonna be waaay more :) Thanks a lot!

2021-02-17 10:40 UTC, merged