Fix irregular comment count buttons
forem/forem pull request #12724
Opened 2021-02-17 22:03 UTC by jacobherrington

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Fixes https://github.com/forem/forem/issues/12513

## Related Tickets & Documents

## QA Instructions, Screenshots, Recordings

All articles without comments should now read "Add comment" instead of "0 comments" when rendered in the feed.

The seed data should include some articles without comments, refreshing a few times on master should result in at least one "0 comments" example. After applying this commit, that won't happen anymore. :smile: 

## Added tests?

- [ ] Yes
- [x] No, and this is why: afaik there is no test coverage here and adding it might be a pretty big task that the issue is not scoped for
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: minor UI bugfix

2021-02-18 09:14 UTC, ludwiczakpawel requested changes
I can still see some cards without any indicator:

**Profile:**

![image](https://user-images.githubusercontent.com/108287/108333900-b09b3f80-71d1-11eb-9480-95aa42439207.png)

**Tag:** 

![image](https://user-images.githubusercontent.com/108287/108333940-bdb82e80-71d1-11eb-8502-385d55142b5b.png)


But it does seem to work just fine on home page.

2021-02-19 19:52 UTC, jacobherrington commented
@ludwiczakpawel Good catch! I didn't realize some of the articles on those pages were handled by different code :cold_sweat: Maybe we can deal with that duplicated logic in a future clean-up, so that all articles are rendered by the same logic (ideally, the same code).

I also added a couple of quick regression tests to help determine if this happens again (specifically those tests are for the homepage and the `/t/` pages).

2021-02-22 10:00 UTC, ludwiczakpawel approved these changes

2021-02-22 12:21 UTC, aitchiss approved these changes
LGTM 😄

2021-02-22 18:11 UTC, merged