Add new DUS for backfilling usernames
forem/forem pull request #12739
Opened 2021-02-19 03:48 UTC by citizen428

## What type of PR is this? (check all applicable)

- [X] Bug Fix

## Description

The data update script in #12728 only updated 3 out of 45 users. This was due to the remaining 42 users being invalid for other reasons (duplicate emails or too long emails). To be able to move on with the original task of adding a non-null constraint I made a new script using `update_column` to avoid this problem and we have to deal with the email validation problems separately.

## Related Tickets & Documents

#2207 

## Added tests?

- [X] Yes

2021-02-19 04:05 UTC, Zhao-Andy approved these changes
LGTM! Do we want to run the manual callbacks for username updates?

2021-02-19 04:09 UTC, citizen428 commented
@Zhao-Andy These are the same 42 users from the support request I opened for you, maybe it can be done at the end of that, once we know exactly which ones are left?

2021-02-19 10:07 UTC, rhymes approved these changes

2021-02-19 19:19 UTC, Zhao-Andy commented
Hmm so this resolved itself when I cleaned up the users' validation errors. I think we can either close this PR or update this PR to only remove the original DUS code.

2021-02-19 19:34 UTC, Zhao-Andy requested changes
Hmm so this resolved itself when I cleaned up the users' validation errors. I think we can either close this PR or update this PR to only remove the original DUS code?

2021-02-22 02:10 UTC, citizen428 commented
Good point @Zhao-Andy, I think we can just close this.

2021-02-22 02:10 UTC, closed without merging