Update credit purchase button on submit
forem/forem pull request #12760
Opened 2021-02-22 06:55 UTC by citizen428

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

## QA Instructions, Screenshots, Recordings

![2021-02-22 13_50_15-Purchase Credits - DEV Community 🌱 and 8 more pages - Personal - Microsoft​ Edg](https://user-images.githubusercontent.com/47985/108673013-85885700-7515-11eb-880e-ad25e81e1dda.png)

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://docs.forem.com/frontend/accessibility)._

## Added tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2021-02-23 10:02 UTC, aitchiss requested changes
Left a comment about Safari support, and I think we also need to handle the case where an error is returned, switching the button back to its original state. At the moment it continues to show "Submitting..." alongside the returned error:

![Screenshot showing the error state with a button stating submitting](https://user-images.githubusercontent.com/20773163/108827920-187ccc00-75be-11eb-8d7e-0d595b893629.png)

2021-02-23 13:42 UTC, citizen428 commented on app/views/credits/new.html.erb
> +      var button = event.submitter;
I had this at first, then thought `event.submitter` is more elegant. Didn't occur to me to test in Safari, thanks for catching this! 

I'll fix the other thing tomorrow, it was an oversight on my part: the way I had the code structured at first this was never called if there was an error, but that didn't work once a card was saved, so I moved it but apparently never tested a failure scenario again 🤦

2021-02-24 03:51 UTC, citizen428 commented
Thanks for the review @aitchiss, the button now correctly resets when there was an error:

2021-02-24 03:55 UTC, citizen428 commented
Sorry for the rebase and force push, my branch got all funky after I merge back `master` for the DB changes and this was the fastest way to get it cleaned up.

2021-02-24 08:19 UTC, Ridhwana approved these changes
This LGTM with the updated changes.

2021-02-24 10:04 UTC, aitchiss approved these changes
Nice! Tested locally and all looking good to me 👍

2021-02-24 10:44 UTC, merged