Small post Rails 6.1 fixes
forem/forem pull request #13290
Opened 2021-04-07 09:06 UTC by rhymes

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

I ran `bundle install` after #13280 and ran `bundle exec rails db:migrate` after we upgraded to Rails 6.1.

See inline comments for further info

## Related Tickets & Documents

#13280
#11333 

## Added tests?

- [ ] Yes
- [x] No, and this is why: not needed
- [ ] I need help with writing tests

2021-04-07 09:09 UTC, rhymes commented on Gemfile.lock
> +  x86_64-darwin
This is what `bundle install` on macOS Catalina left me with

2021-04-07 09:09 UTC, rhymes commented on db/schema.rb
> +# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
this is changed automatically by Rails 6.1

2021-04-07 09:09 UTC, rhymes commented on db/schema.rb
> +    t.check_constraint "username IS NOT NULL", name: "users_username_not_null"
Rails 6.1 finally dumps check constraints, see https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/Table.html#method-i-check_constraint

@citizen428 will be happy :D

2021-04-07 14:50 UTC, joshpuetz requested changes
A quick suggestion related to versions in the Gemfile.lock, otherwise looks good to me!

2021-04-07 14:50 UTC, joshpuetz commented on Gemfile.lock
>    arm64-darwin-20
```suggestion
  arm64-darwin
```

Suggest removing the version number

2021-04-07 14:50 UTC, joshpuetz commented on Gemfile.lock
>    x86_64-darwin-20
```suggestion
```

Suggest removing these lines as we are covered by the line `x86_64-darwin`

2021-04-07 16:09 UTC, rhymes commented
@joshpuetz done, thank you!

2021-04-07 16:10 UTC, maestromac approved these changes

2021-04-07 16:20 UTC, jgaskins approved these changes
Nice! 🙌🏼

2021-04-07 18:14 UTC, rhymes commented
There's a broken spec, because now that Rails enforces the check constraints, we need to adjust a data update script. I'm on it!

2021-04-08 04:55 UTC, citizen428 approved these changes

2021-04-08 12:57 UTC, joshpuetz approved these changes

2021-04-08 12:58 UTC, joshpuetz approved these changes

2021-04-08 12:58 UTC, merged