re-enable test
forem/forem pull request #13412
Opened 2021-04-15 10:03 UTC by aitchiss

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://docs.forem.com/frontend/accessibility)._

## Added tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2021-04-20 14:52 UTC, nickytonline requested changes
I'm getting a test failure for the last test.

![image](https://user-images.githubusercontent.com/833231/115417175-68df6700-a1c6-11eb-984c-6acc5f2267cb.png)

Also, a small request change and a suggestion.

2021-04-20 14:52 UTC, nickytonline commented on cypress/integration/articleFlows/commentOnArticle.spec.js
> +const getCommentCombobox = () =>
Documentation (blocking): Leave a comment in the code as to why we are not using aliases and these functions instead.

nitpick (non-blocking): Move these functions to the top of the file within the first describe.

2021-04-20 15:05 UTC, aitchiss commented
> I'm getting a test failure for the last test.

@nickytonline that test isn't one that's currently disabled or looked at in this PR. Maybe we want to consider skipping _all_ of the mention autocomplete tests (apart from the first one we're reintroducing here) and bringing them back in one by one when we're convinced they're stable?

I don't want to just disable everything, but at the same time I think the plan of bringing this one test back and then rolling out the approach to the other tests once we're sure that it's stable makes sense. I haven't seen that particular test flaking locally for me in CI, but clearly it's not super reliable.

2021-04-20 15:16 UTC, nickytonline commented
> > I'm getting a test failure for the last test.
> 
> @nickytonline that test isn't one that's currently disabled or looked at in this PR. Maybe we want to consider skipping _all_ of the mention autocomplete tests (apart from the first one we're reintroducing here) and bringing them back in one by one when we're convinced they're stable?
> 
> I don't want to just disable everything, but at the same time I think the plan of bringing this one test back and then rolling out the approach to the other tests once we're sure that it's stable makes sense. I haven't seen that particular test flaking locally for me or in CI, but clearly it's not super reliable.

Ahh, didn't realize that one wasn't part of your changes. 🙃 It could be something on my local. If it's been reliable on CI, let's not worry for the moment and stick to the rollout out we discussed of unflaking one test at time until it's stable for a few days. 😎

So just the small request change and this is good to go then.

2021-04-21 09:04 UTC, aitchiss commented
@nickytonline added that comment, and removed aliases from the other enabled tests in that file 🙌

2021-04-22 14:15 UTC, nickytonline approved these changes
LGTM! Hopefully we can say adieu to this flakiness. 😎

2021-04-22 16:15 UTC, rhymes approved these changes
LGTM!

2021-04-22 16:15 UTC, merged