🐛 Fix new comment dropdown issue
forem/forem pull request #13661
Opened 2021-05-05 11:00 UTC by Link2Twenty

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
When you create a new comment on the comments page then try and access its menu no menu opens. This was caused by an error in JS.

## Related Tickets & Documents
Loosely related to #13365

## QA Instructions, Screenshots, Recordings

### Before
![forem_new-comment-issue](https://user-images.githubusercontent.com/3534427/117131120-ed221480-ad98-11eb-8f9e-3499dde9b336.gif)

### After
![forem_fix-new-comment](https://user-images.githubusercontent.com/3534427/117131134-f1e6c880-ad98-11eb-88ce-34277551a209.gif)

### UI accessibility concerns?
N/A

## Added tests?

- [ ] Yes
- [x] No, and this is why: old tests will still work
- [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?
N/A

## [optional] What gif best describes this PR or how it makes you feel?

![Not a gross bug anymore](https://img.17qq.com/images/sscwewwaqx.jpeg)

2021-05-05 21:55 UTC, nickytonline requested changes
Thanks for the PR @Link2Twenty! A couple change requests.

2021-05-05 21:55 UTC, nickytonline commented on app/assets/javascripts/initializers/initializeCommentsPage.js.erb
> +  const commentsCountDiv = document.getElementsByClassName("js-comments-count")[0];
Refactor (blocking): Use document.querySelector('.js-comments-count').

2021-05-05 21:55 UTC, nickytonline commented on app/assets/javascripts/initializers/initializeCommentsPage.js.erb
> +  const commentsCountData = parseInt(commentsCountDiv.dataset.commentsCount) + 1;
Refactor (blocking): Add a [radix](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#parameters) to `parseInt` for base 10, e.g. `parseInt(commentsCountDiv.dataset.commentsCount, 10)` or use `Number(commentsCountDiv.dataset.commentsCount)`

![image](https://user-images.githubusercontent.com/833231/117214390-bbc23c80-adca-11eb-9bc3-a7d03339178b.png)

2021-05-05 21:57 UTC, Link2Twenty commented
For future reference, when fixing a bug like this should I modernise adjacent code, even if it's not code I'm actively working on?

2021-05-05 22:02 UTC, nickytonline commented
> For future reference, when fixing a bug like this should I modernise adjacent code, even if it's not code I'm actively working on?

Thanks for asking @Link2Twenty! I just mentioned it as it's a small fix since we're in this piece of code. If it was a larger refactor noticed while fixing an issue, I'd create a separate issue for that.

2021-05-06 11:35 UTC, nickytonline approved these changes
Thanks @Link2Twenty! 🚀

2021-05-06 12:56 UTC, ludwiczakpawel approved these changes

2021-05-06 13:06 UTC, merged