Meg gutshall/liquid tag company avatars 11880
forem/forem pull request #13928
Opened 2021-06-07 07:12 UTC by meg-gutshall

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This was part of the Live Code Pairing series with @nickytonline and @cmgorton. For this stream we worked on fixing the way avatars appear in liquid tag links when a post is written by a user, but under an organization account. The avatar was not rendering as displayed on the front page, it was only showing the user's avatar.

## Related Tickets & Documents

Fixes #11880 

## QA Instructions, Screenshots, Recordings

This is what we were looking for on the Liquid tags:
<img width="885" alt="Screen Shot 2021-06-07 at 2 48 58 AM" src="https://user-images.githubusercontent.com/37842352/120973924-8c8e4a80-c73d-11eb-9166-55bcc157aa91.png">

This is the issue that we were seeing:
<img width="886" alt="Screen Shot 2021-06-06 at 10 39 26 PM" src="https://user-images.githubusercontent.com/37842352/120973970-99ab3980-c73d-11eb-9cba-11c39aa8d620.png">

Here is the fix:
<img width="1250" alt="Screen Shot 2021-06-07 at 2 48 35 AM" src="https://user-images.githubusercontent.com/37842352/120974043-aaf44600-c73d-11eb-84bb-d7ce45df03a3.png">

Here's an alternate with the author pointing solely to the organization:
<img width="1357" alt="Screen Shot 2021-06-07 at 2 46 58 AM" src="https://user-images.githubusercontent.com/37842352/120974168-ce1ef580-c73d-11eb-9994-694375f1f4a2.png">

### UI accessibility concerns?

The images still retain `alt` tags and they're both wrapped in the hyperlink that will redirect to the article's author.

## Added tests?

- [ ] Yes
- [x] No, and this is why: The existing tests would need a decent amount of work to get to the granularity needed to actually test if this feature was working and I don't have that kind of time right now.
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2021-06-07 21:00 UTC, jgaskins reviewed
Hey Meg, thanks for the PR! :100: It looks great! Just a couple nitpicks — and one of them is just a suggestion that I'm not even sure is feasible. :joy:

Admittedly I haven't watched the full stream so I don't know if y'all talked about these changes or not. Either way, it was great to see a Ruby for Good friend come through my GitHub notifications. 🙌🏼

2021-06-07 22:14 UTC, meg-gutshall commented on db/schema.rb
> +    t.integer "user_id", null: false
Sure thing! I think that was automatically added when I ran the migrations. (I couldn't get Docker to cooperate with me so I ended up building locally instead.)

2021-06-07 22:16 UTC, meg-gutshall commented on app/views/articles/_liquid.html.erb
> +    </a>
Okay, I'll give this another go and see what I can do. I was fading when I got this in last night so I can probably refactor a bit in here.

2021-06-07 22:21 UTC, meg-gutshall commented
Oh hi there @jgaskins! Yes, so lovely to see another gooder! 😁 

![](https://media1.giphy.com/media/31gMYr4CPtHq0/giphy.gif)

BTW, when I tried to run the RSpec tests last night before submitting, I saw that the test db hadn't been created in the initial setup. Is there a different command I need to run for that?

Thank you for the helpful feedback! I will try to make time this weekend to submit an update.

2021-06-11 12:03 UTC, aitchiss requested changes
I tested this locally and it's working great!

I made sure there's no regression for links in posts published before the changes, as well as for newly added ones, and all looks good to me 👍 

I just have a couple of very minor change requests to enhance the experience for screen reader users. Let me know if you have any questions, and thanks very much for these changes!

2021-06-11 12:03 UTC, aitchiss commented on app/views/articles/_liquid.html.erb
> +        <img src='<%= Images::Profile.call(article.user.profile_image_url, length: 150) %>' alt='<%= "#{article.user.username} image" %>'>
nitpick (blocking) - like the example above, removing the word "image" helps reduce unnecessary noise for screen reader users. I know it was like this before, but it's a great opportunity to sweep it up now 🙌 

```suggestion
        <img src='<%= Images::Profile.call(article.user.profile_image_url, length: 150) %>' alt='<%= "#{article.user.username}" %>'>
```

2021-06-14 03:24 UTC, meg-gutshall commented
@aitchiss I appreciate the work you put into the testing portion of this! I agree that alt tag content sounds much better. I've accepted both of your suggested changes.

@citizen428 I did run `bin/setup` per the instructions but somehow the test database did not get created, only the development database. Here is the content of my `test.log` file if that helps any:

```
Unset ENV variable: IMGPROXY_KEY.
Unset ENV variable: IMGPROXY_SALT.
Unset ENV variable: RELEASE_FOOTPRINT.
** [Honeybadger] Initializing Honeybadger Error Tracker for Ruby. Ship it! version=4.8.0 framework=rails level=1 pid=34131
Unset ENV variable: COMMUNITY_COPYRIGHT_START_YEAR.
```

2021-06-14 12:45 UTC, aitchiss commented
@meg-gutshall - this is looking great - thanks for making those tweaks!

I noticed there are some specs failing
- The "frontend tests" build job failed due to a known flakey test - I don't think it's anything to do with your code and I've restarted it now 🙂 
- The other failed build job is because of the changes to the `alt` tag - in `spec/liquid_tags/link_tag_spec.rb` we'll need to update the `correct_link_html` to reflect the new alt text. Let me know if you have any trouble doing this - hopefully just a quick change!

Thanks again - once the specs are passing I think this is good to go 🚀

2021-06-21 03:16 UTC, citizen428 commented
Hi @meg-gutshall thanks for all your work on this PR so far, it's much appreciated! 🥇 Is there anything we can do to help you push this over the finish line?

2021-06-21 16:50 UTC, meg-gutshall commented
Hi @aitchiss and @citizen428! Thank you for your help and patience. I'm finishing up a coding bootcamp with a deadline of 6/30 (and *just starting* my final project today 😬 ) so I need to prioritize that.

I can finish up this PR in early July if that's okay with you. If it can't wait, I'm okay with co-authoring this PR. I feel like @aitchiss should get co-author recognition if she hasn't already for her suggested changes.

Please let me know how you would like to proceed!

2021-06-22 01:50 UTC, citizen428 commented
I'm fine either way, I'll leave it up to @aitchiss 😃

2021-06-22 09:40 UTC, aitchiss commented
That's exciting about your final project @meg-gutshall!

We're not in any rush, but I think there's only a teeny change to the specs needed, so I'm happy to have a look at that and then hopefully we can get this merged 😄  You've already done 99.9% - happy to help push it over the line!

2021-06-22 15:09 UTC, meg-gutshall commented
Woohoo! Thank you tons! Time for a celebration dance!!!

![](https://media0.giphy.com/media/3ornkdtVzQfIRpwfug/giphy.gif)

2021-06-22 15:55 UTC, cmgorton commented
> Woohoo! Thank you tons! Time for a celebration dance!!!


Woohoo! Thanks for the contribution Meg🎉

And thanks team for all the help 🙏

2021-06-22 17:20 UTC, nickytonline commented
Nice to see this completed @meg-gutshall! I'm going to link the stream to this PR for folks to see it come full circle.

Thanks again for your contribution to the Forem codebase! 😎

<p align="center">
	<a href="https://www.youtube.com/watch?v=lpdzrcx60Ho&list=PL8Bb2WLXhUaBGrYRnmDaF73LDCjEGzjIE&index=2"><img src="https://user-images.githubusercontent.com/833231/122970784-50bdcc80-d35c-11eb-86fe-1f943b68fce2.png" /></a>
</p>

2021-06-23 03:06 UTC, citizen428 commented on db/schema.rb
> +    t.integer "user_id", null: false
@meg-gutshall I fixed this for you so we can get this PR merged 😃

2021-06-23 03:24 UTC, citizen428 approved these changes

2021-06-23 03:25 UTC, merged