Fix Prop Types Error #14837
forem/forem pull request #14889
Opened 2021-10-01 23:57 UTC by papuruth

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description
As per issue no. #14837 I have fixed prop types errors for Button, ButtonGroup, Modal, and articlePage components.

## Related Tickets & Documents
#14837 

## QA Instructions, Screenshots, Recordings
I don't believe any new tests would be required for these changes.

## Added/updated tests?
- [x] No, as because it doesn't seem legit to write UT for these changes.

## [optional] What gif best describes this PR or how it makes you feel?

![Two on Behance](https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5eeea355389655.59822ff824b72.gif)

2021-10-01 23:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/forem/forem?pullRequest=14889) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/forem/forem?pullRequest=14889) before we can accept your contribution.<br/><hr/>**Papu Kumar** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/forem/forem?pullRequest=14889) it.</sub>

2021-10-04 08:07 UTC, aitchiss requested changes
Thanks for taking this on! It's looking great, but I just have a couple of small change requests - let me know if I can assist at all!

2021-10-04 08:13 UTC, papuruth commented on app/javascript/crayons/ButtonGroup/ButtonGroup.jsx
> +  ).isRequired,
Exactly we should pass null @aitchiss

2021-10-04 08:21 UTC, papuruth commented on app/javascript/common-prop-types/default-children-prop-types.js
> +  PropTypes.object,
I'll check on local if it isn't causing any problem then I'll push a commit

2021-10-04 08:32 UTC, papuruth reviewed
I have pushed the changes please review

2021-10-04 12:37 UTC, aitchiss approved these changes
Thanks for making those changes! ✨

2021-10-05 06:25 UTC, citizen428 approved these changes

2021-10-05 08:58 UTC, merged