Safari CSS gradient bug #14311
forem/forem pull request #14893
Opened 2021-10-02 06:40 UTC by valtism

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Transition to a transparent version of the same background color with
no opacity so that safari transitions through correctly.

Switch all --story-comments-bg themes to hexadecimal, fixes no fade bug
in "Pink" theme.

## Related Tickets & Documents

#14311 

## QA Instructions, Screenshots, Recordings

Please see the linked issue for screenshots of the issue and how it should look with this fix.

## Added/updated tests?

- [ ] Yes
- [x ] No, and this is why: I don't think this CSS change needs tests.
- [ ] I need help with writing tests

2021-10-02 06:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/forem/forem?pullRequest=14893) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/forem/forem?pullRequest=14893) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/forem/forem?pullRequest=14893) it.</sub>

2021-10-02 06:41 UTC, valtism commented
I would have preferred to apply an alpha to the existing variable, but this was not possible with plain CSS variables.

2021-10-05 07:56 UTC, ludwiczakpawel requested changes
hey @valtism , great to see this fix coming! FYI, we now have [variables for semi transparent base colors](https://github.com/forem/forem/blob/main/app/assets/stylesheets/config/_colors.scss#L31-L51) which I think you could utilize here in a bit more efficient way. I'd be also happy to have something like this:

```
--story-comments-bg: 249, 249, 249; // this is RGB value - it's hacky but ¯\_(ツ)_/¯
--story-comments-bg-top: rgba(var(--story-comments-bg), 0);
--story-comments-bg-bottom: rgba(var(--story-comments-bg), 1);
```

2021-10-05 09:40 UTC, valtism commented
@ludwiczakpawel Oh wow, this is exactly what I wish I had when I was making this PR! I'll refactor it to use them now.

2021-10-05 10:22 UTC, closed without merging