Preventing author profile from going transparent
forem/forem pull request #15478
Opened 2021-11-23 18:59 UTC by jeremyf

## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description

Prior to this change, when you would hover over an author profile that
was "close to" the bottom of the page, the card would be transparent
instead of the expected opaque.

With this change, when you hover over an author profile that is "close"
to the bottom of the page, the card renders as an opaque card.

Now why does this work?  I don't really know, except to say that a
`display: table` imperative is a more "chunky" display element than a
block.  I would love for someone to explain why this works.

Tested against on MacOS Safari, Firefox, and Chrome.

https://developer.mozilla.org/en-US/docs/Web/CSS/display

## Related Tickets & Documents

Fixes #15290

## QA Instructions, Screenshots, Recordings

Open to the homepage, and scroll so that the bottom-most visible article card is position just above the browser window.  Hover over the author.  With this fix, the card should be opaque and rendered past the bottom of the view frame.

Without this commit, the card will be transparent-ish and the text from the article card will "bleed" through.

### UI accessibility concerns?

Uncertain.

## Added/updated tests?

- [x] No, and this is why: I don't believe it's necessary.

## [Forem core team only] How will this change be communicated?

- [x] This change does not need to be communicated, and this is why not: it is a small bug fix for a UI edge case (albeit not an extreme edge case but a somewhat common one).

2021-11-23 20:36 UTC, ludwiczakpawel requested changes
So here's what happens _usually_ (but not for these profile-preview dropdowns): dropdown component is being attached to the bottom element of its trigger unless the trigger (or the dropdown, I'm not sure) is close to the bottom edge of the viewport - in that case the dropdown changes its position and appears ABOVE the trigger (see "Subscribe" component on top of the Discussion section on a post view for a properly working example). Close enough to be actually "cut off".  That behavior is achieved by applying [`reverse` class](https://github.com/forem/forem/blob/e7af2bfc86d52322d79d4186cb4cc69c4e8ddd92/app/assets/stylesheets/components/dropdowns.scss#L20-L24) which happens with JS.

Why it doesn't work for these particular dropdowns? Because of [classes specificity](https://www.w3schools.com/css/css_specificity.asp) - we have [applied some custom styling](https://github.com/forem/forem/blob/main/app/assets/stylesheets/components/profile-preview-card.scss#L10) to these specific (profile preview) dropdowns so they became more important than the ones we defined on [the component level](https://github.com/forem/forem/blob/main/app/assets/stylesheets/components/dropdowns.scss#L20-L24).

I think there was a reason why we added that custom styling but I'm not 100% sure why exactly. Maybe @nickytonline or @aitchiss know.

Even though the `display: table` may fix the bug at first glance, (which btw. really surprised me! :D) it doesn't fix the core issue and it certainly doesn't bring bring the `revert` functionality.

I think there are two solutions:

1. Change the specificity of that custom CSS so it doesn't overwrite the component CSS - but this may not be trivial...
2. Add `!important`s to [the component's `revert` styling](https://github.com/forem/forem/blob/main/app/assets/stylesheets/components/dropdowns.scss#L20-L24) - even though we tend to avoid using `!important` in our CSS, I think using it here is justified.

2021-11-24 08:21 UTC, aitchiss commented
> I think there was a reason why we added that custom styling but I'm not 100% sure why exactly. Maybe @nickytonline or @aitchiss know.

To be honest I can't remember 😆  I'm happy to dig into it and refresh my memory though, just let me know if I can help. It's entirely possible that we don't need that level of specificity and it was just an oversight.

I'm not sure why the `top` styling and `reverse` class would affect the transparency of the background though? As far as I understand, the card is being positioned properly, but the background becomes transparent

2021-11-24 08:40 UTC, aitchiss commented
For what it's worth, I think the root cause of this issue will be in the listener which repositions the dropdown - looks like it's not functioning properly / could be refactored to use the `reverse` class with a bit of investigation: https://github.com/forem/forem/blob/86e4c39e31ddae896e8f70581b73435b25d935cd/app/javascript/utilities/dropdownUtils.js#L22

2021-11-24 09:28 UTC, ludwiczakpawel commented on app/assets/stylesheets/components/dropdowns.scss
> +  top: 100%;
Turns out most of our dropdown are positioned this way so it made sense to have it there.

2021-11-24 09:28 UTC, ludwiczakpawel commented on app/assets/stylesheets/components/dropdowns.scss
> +  margin-top: var(--su-1);
Not really part of this PR but I wanted to sneak it in.

2021-11-24 09:28 UTC, ludwiczakpawel commented on app/assets/stylesheets/components/profile-preview-card.scss
> +    animation: hoverAppear var(--dropdown-hover-delay);
i couldn't stand it 🤷‍♂️  :D

2021-11-24 09:31 UTC, ludwiczakpawel commented on app/javascript/CommentSubscription/CommentSubscription.jsx
> -
So one of our dropdowns (for Discussion's _Subscribe_ button) was actually doing this repositioning but it was completely custom for some reason (I guess it was created BEFORE the `reverse` magic). So I removed it and updated the component itself with `reverse` magic handler.

2021-11-24 09:38 UTC, ludwiczakpawel commented on app/views/articles/_actions.html.erb
> -      <div id="article-show-more-dropdown" class="crayons-dropdown side-bar left-2 right-2 m:right-auto m:left-100 s:left-auto bottom-100 m:bottom-auto m:top-0 mb-1 m:mb-0">
little fix and cleanup

2021-11-24 09:40 UTC, ludwiczakpawel commented
After chatting with @aitchiss we decided to do a little cleanup. And apparently there was a bit more refactor needed 🤷... I left some comments in the code. Anyway, things should now work properly.

2021-11-24 09:43 UTC, ludwiczakpawel approved these changes
I initially requested changes, but I have also pushed some changes afterwards... And I can now only "approve" it (I can't take back my request changes), so extra two reviews would be appreciated 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/108287/143213846-28d61456-c01c-4355-8c21-056c96cf76d4.png)

2021-11-24 09:49 UTC, aitchiss approved these changes
This all looks good to me - nice one!

2021-11-24 09:49 UTC, aitchiss commented on app/assets/stylesheets/components/profile-preview-card.scss
> +    animation: hoverAppear var(--dropdown-hover-delay);
hahaha woops

2021-11-24 14:07 UTC, fdoxyz approved these changes
Tried it out locally and seems like it works great for me 🙌

2021-11-24 14:37 UTC, msarit approved these changes
All changes made appear to work well! I replicated the bug on DEV; this PR fixes the issue, and also appears to shift the pop-up profile higher when it renders close to the browser-edge.

Great work all around!

2021-11-24 14:38 UTC, merged