Use the feed source url when the feed url (from links) is empty
forem/forem pull request #15497
Opened 2021-11-24 18:55 UTC by djuber

This probably should just be using @feed_source_url always to make a
base path for absolute paths without a hostname, rather than expecting
this from the feed.

An example why we should not be using @feed.url would be
individual posts at domain/slug but the "index" page at
domain/blog (with a generic screen on /), and images hosted from
/assets/ without /blog/ anywhere in the asset path.

Partial fix for #15488

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2021-11-24 18:57 UTC, jeremyf approved these changes

2021-11-24 19:01 UTC, djuber commented on app/services/feeds/assemble_article_markdown.rb
> +        @feed.url.presence ||
is there a good reason to prefer @feed.url (from links) even if it is present? From what I can tell from https://validator.w3.org/feed/docs/atom.html#recommendedFeedElements ,  that implementation in feedjira is a little optimistic (it just uses the last link that's not the feed itself ?).

2021-11-24 20:40 UTC, djuber commented on app/services/feeds/assemble_article_markdown.rb
> +        URI.parse(@item.url).then do |uri|
are there ever rss items without a url?

https://web.resource.org/rss/1.0/spec#s5.5 the RSS spec requires there be a valid uri for each item
https://validator.w3.org/feed/docs/atom.html#requiredEntryElements the atom spec uses id and requires it be a unique URI.

2021-11-29 20:22 UTC, joshpuetz requested changes
This seems like a sensible change but I'm curious about testing: do existing test cover this change?

2021-11-30 06:01 UTC, citizen428 approved these changes

2021-12-09 20:08 UTC, merged