Reduce Width of "Community Name" Field and "Finish" Button on Creator Settings Form
forem/forem pull request #15725
Opened 2021-12-10 12:57 UTC by juliannatetreault

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2021-12-10 13:24 UTC, juliannatetreault commented
Rather than reducing the width of the "Community Name" field and "Finish" button, I adjusted the width of the "Community Name" field, "Finish" button, and "Brand Color" field to all be the same. The reason being that when I changed the width of just the "Community Name" field and the "Finish" button to match that of the "Brand Color" field, not only did the form look off in general, but it also looked quite different from the design shown in the design feedback linked in the issue in the PR description and to the original Creator Onboarding design RFC.

For reference, this is what the form looked like when I reduced the width of the "Community Name" field and "Finish" button to match the "Brand Color" field:
![Screen Shot 2021-12-10 at 6 24 06 AM](https://user-images.githubusercontent.com/32834804/145580779-32a8434d-cd90-415c-95ce-08a3d0ad3df7.png)

This all being said, I'm happy to adjust the form to the above design if folks decide they prefer it, but personally thought that the current form layout looked more like a "block" (the ultimate goal of this change).

cc @Ridhwana @anujbhavsar96 @nickytonline @JennieOcken

2021-12-10 15:05 UTC, Ridhwana approved these changes
This looks good to me and makes sense but maybe just check with @anujbhavsar96.

2021-12-10 15:18 UTC, nickytonline requested changes

2021-12-10 15:18 UTC, nickytonline commented on app/views/admin/creator_settings/_form.html.erb
> +  <%= text_field_tag :community_name, "", placeholder: "Climbing Life", class: "crayons-textfield flex w-100 m:w-100", required: true %>
Refactor (blocking): No need for any width CSS utility classes or the `flex` CSS utility class. The parent, `.crayons-field` has its display set to flex with a flex-flow of column.

![image](https://user-images.githubusercontent.com/833231/145596039-1460a740-8887-458f-bc55-52cf02fabe5a.png)

```suggestion
  <%= text_field_tag :community_name, "", placeholder: "Climbing Life", class: "crayons-textfield", required: true %>
```

2021-12-10 15:18 UTC, nickytonline commented on app/views/admin/creator_settings/_form.html.erb
> +  <div class="flex w-100 m:w-100 crayons-field">
Refactor (blocking): No need for width CSS utility classes as the `flex` CSS utility class will take the entire space available and adjust as the page resizes. Also, the `.crayons-field` already sets the `display` to `flex`.

![image](https://user-images.githubusercontent.com/833231/145596039-1460a740-8887-458f-bc55-52cf02fabe5a.png)

```suggestion
  <div class="crayons-field">
```

2021-12-10 15:18 UTC, nickytonline commented on app/views/admin/creator_settings/new.html.erb
> +        <%= submit_tag "Finish", class: "crayons-btn btn--primary w-100 m:w-100" %>
Refactor (blocking): No need for any width CSS utility classes or the `flex` CSS utility class. The parent, `.crayons-field` has its display set to flex with a flex-flow of column.

![image](https://user-images.githubusercontent.com/833231/145596039-1460a740-8887-458f-bc55-52cf02fabe5a.png)

```suggestion
        <%= submit_tag "Finish", class: "crayons-btn btn--primary" %>
```

2021-12-10 16:28 UTC, nickytonline approved these changes
Thanks for making the changes @juliannatetreault! 🚀

2021-12-10 16:53 UTC, merged

2021-12-13 03:56 UTC, anujbhavsar96 commented
This looks great @juliannatetreault 🚀

I think it'll look better if we keep the width 400/480px. Why this? Because whatever the inputs we are asking are not huge multi-word inputs. So there is no need to have bigger field sizes. 

![image](https://user-images.githubusercontent.com/84626054/145749834-80cf875e-822c-4abe-be44-1c35fc8d4cec.png)