Storybook improvements
forem/forem pull request #15860
Opened 2021-12-22 12:49 UTC by ludwiczakpawel

## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature
- [x] Documentation Update

## Description

This PR does few things:

1. It implements official addons for switching background color between `var(--body-bg)` and `var(--card-bg)` as these are usually two backgrounds we put our components against. We this should make it easier to test it.
2. It reimplements theme switcher so it's no longer "built into" the story Canvas - instead it utilizes an add-on made specifically for this and uses toolbar as a switcher container. Previous solution was a bit hacky.

That 2nd change required transitioning `_colors.scss` and `dark.scss` to simply be CSS files (instead of SCSS). There are also two side effect - benefits:
1. Making any changes to dark.scss required restarting the storybook which wasn't very efficient while testing. Now we don't need that. This was also an issue in the product itself.
2. It will make it easier to easily switch themes on the fly (when we're ready to do it) in /settings/customization without necessarily refreshing the page. 

It also cleans up few other things in the Storybook.

## QA Instructions, Screenshots, Recordings

https://user-images.githubusercontent.com/108287/147095209-724511e4-5634-4650-a7cb-30c694453032.mov

## Added/updated tests?

Not need.

## [Forem core team only] How will this change be communicated?

In Forem.team post.

2021-12-22 12:52 UTC, ludwiczakpawel commented on app/javascript/.storybook/manager.js
> -  brandTitle: '🖍️ Crayons 🖍️',
whatevaaaaa ✂️ ✂️ ✂️

2021-12-22 12:52 UTC, ludwiczakpawel commented on app/javascript/.storybook/preview.js
> -export const Foo = () => <Component />;
Some legacy stuff that wasn't used anywhere and in fact was throwing errors in console...

2021-12-22 12:53 UTC, ludwiczakpawel commented on app/javascript/.storybook/preview.js
> -      order: [
This was not only outdated but also unnecessary.

2021-12-22 15:45 UTC, nickytonline commented on app/javascript/.storybook/main.js
> +    '@etchteam/storybook-addon-css-variables-theme',
For folks interested, check out https://github.com/etchteam/storybook-addon-css-variables-theme

2021-12-22 15:45 UTC, nickytonline commented on app/javascript/.storybook/preview.js
> -function addStylesheet(theme = '') {
Glad to see we don't need this custom bit anymore.

2021-12-22 16:01 UTC, nickytonline approved these changes
Thanks for the cleanup @ludwiczakpawel!

2021-12-22 16:17 UTC, ludwiczakpawel commented on app/javascript/.storybook/manager.js
> -  brandTitle: '🖍️ Crayons 🖍️',
Yea, I'll add something in :)

2022-01-05 10:02 UTC, aitchiss requested changes
This is really cool - love these improvements. I've requested a small change to get the HTML copy/paste working again, but it's just more ✂️

2022-01-05 10:02 UTC, aitchiss commented on app/javascript/.storybook/preview.js
>    },
(blocking) - this needs to be removed now - it was added before to make sure the generated HTML code didn't include the theme switcher. Now that we've also removed the `div` with `id="story-content"` the HTML preview is broken, but if we just remove this whole chunk it'll all work fine 👍 
```suggestion
```

2022-01-14 02:56 UTC, citizen428 approved these changes

2022-01-14 09:40 UTC, aitchiss approved these changes

2022-01-14 10:06 UTC, merged