app/validators i18n
forem/forem pull request #16166
Opened 2022-01-18 15:58 UTC by yheuhtozr

## What type of PR is this? (check all applicable)

- [X] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

i18n for scripts under app/validators.

## Related Tickets & Documents

#14888

## QA Instructions, Screenshots, Recordings

### UI accessibility concerns?

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [X] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2022-01-18 16:28 UTC, jeremyf approved these changes

2022-01-18 16:38 UTC, nickytonline requested changes
Thanks so much for the PR @yheuhtozr! One small change request.

2022-01-18 16:38 UTC, nickytonline commented on app/validators/bytesize_validator.rb
> +  # ERROR_MISSING_OPTIONS_MESSAGE = I18n.t("validators.bytesize_validator.specify_the_maximum_option").freeze
Refactor (blocking): Since this is unused and currently commented out, remove it since it's dead code.

```suggestion
```

2022-01-19 03:28 UTC, citizen428 approved these changes

2022-01-19 10:25 UTC, nickytonline approved these changes
Looks great @yheuhtozr! 🚀

2022-01-19 10:25 UTC, merged