Updating listings_controller.rb and fixing issue :->  17683
forem/forem pull request #17685
Opened 2022-05-15 11:20 UTC by MdSahil-oss

## What type of PR is this? (check all applicable)

 ✅ Bug Fix

## Description
This PR fixes #17683 .

## Related Tickets & Documents

- Related Issue #17683

## QA Instructions, Screenshots, Recordings
This is a code error fix so no need to show any screenshots, Recordings.

### UI accessibility concerns?
No

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
 ✅ I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2022-05-15 11:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/forem/forem?pullRequest=17685) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/forem/forem?pullRequest=17685) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/forem/forem?pullRequest=17685) it.</sub>

2022-05-16 13:21 UTC, jeremyf requested changes

2022-05-16 13:21 UTC, jeremyf commented on app/controllers/admin/listings_controller.rb
> +      @listing = Listing.find(params[:id])
Thanks for the contribution.  We already have the `@listing` from the `create` method.  We shouldn't need to re-find the object.

Were you able to run this in the application to verify behavior?

2022-05-16 17:09 UTC, jeremyf commented on spec/requests/admin/listings_spec.rb
> +      let!(:listing) { create(:listing, published: true) }
```suggestion
      let!(:listing) { create(:listing, published: false) }
```

2022-05-16 17:09 UTC, jeremyf commented on spec/requests/admin/listings_spec.rb
> +            listing: { published: "0" }
```suggestion
            listing: { published: "1" }
```

2022-05-16 17:09 UTC, jeremyf commented on spec/requests/admin/listings_spec.rb
> +        end.to change { listing.reload.published? }.from(true).to(false)
```suggestion
        end.to change { listing.reload.published? }.from(false).to(true)
```

2022-05-16 17:10 UTC, jeremyf commented
Thank you for the contribution; I have some suggestions as we want to test going from published to unpublished and unpublished to published.

2022-05-16 18:52 UTC, jeremyf commented
@MdSahil-oss we had a broken test that was wrecking havoc on the build.  Could you merge in those changes from the HEAD of the main branch?

2022-05-17 10:47 UTC, MdSahil-oss commented
> @MdSahil-oss we had a broken test that was wrecking havoc on the build. Could you merge in those changes from the HEAD of the main branch?

Do you mean I need to merge update-listing_controller.rb branch into my main branch to remove this test failure

2022-05-17 12:00 UTC, jeremyf commented
> > @MdSahil-oss we had a broken test that was wrecking havoc on the build. Could you merge in those changes from the HEAD of the main branch?
> 
> @jeremyf Do you mean I need to merge update-listing_controller.rb branch into my main branch to remove this test failure

The other way.  You want to merge forem/forem's latest `main` into your `update-listing_controller.rb` branch.  And then you'd push those changes back up to `MdSahil-oss:update-listing_controller.rb`.

2022-05-17 19:11 UTC, jeremyf approved these changes

2022-05-17 19:15 UTC, jeremyf commented
@MdSahil-oss thank you for your contributions; the build should go green and we need one more approval.

2022-05-18 20:28 UTC, maestromac approved these changes
LGTM! Thank you for your contribution @MdSahil-oss !

2022-05-18 20:29 UTC, merged