Convert modals that currently aren't using the Preact modal to the Preact modal
forem/forem pull request #18613
Opened 2022-10-21 07:54 UTC by rt4914

## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Convert modals that currently aren't using the Preact modal to the Preact modal

## Related Tickets & Documents

- Related Issue #16328
- Closes #16328

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility concerns?

None

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: this PR needs update in one test which I was not able to fix.
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

2022-10-25 08:50 UTC, rt4914 commented on app/javascript/admin/__tests__/controllers/config_controller.test.js
> -describe('ConfigController', () => {
Removed this test file as we are using preact-modal now and similar to other instances I have added cypress tests for checking this entire functionality.

2022-10-25 23:51 UTC, fdocr requested changes
Thanks for this @rt4914, this modal looks great and it's awesome to see we're closing these loops (refactors) 🙌🏼 

I did find it impossible to confirm the modal actions though (enable/disable auth providers). Here's a screen recording of what I see. I did notice the Cypress tests didn't include a flow that ensures confirming the modal actually take the action requested. Perhaps I'm missing something?

https://user-images.githubusercontent.com/6045239/197902746-e32abee8-1265-48fb-b7be-939584293224.mov

2022-10-26 08:59 UTC, rt4914 commented
> Thanks for this @rt4914, this modal looks great and it's awesome to see we're closing these loops (refactors) 🙌🏼
> 
> I did find it impossible to confirm the modal actions though (enable/disable auth providers). Here's a screen recording of what I see. I did notice the Cypress tests didn't include a flow that ensures confirming the modal actually take the action requested. Perhaps I'm missing something?
> 
>  confirmation_modal_screen_recording.mov

@fdocr Yes you are right that this feature was missing. I have made following changes:
1. fixed the bug
2. added screenshot of dialogs getting used al all-three places in code
3. added tests to make sure the disable-dialog is also covered.

Thanks.

2022-10-27 12:25 UTC, fdocr approved these changes
Tested and works great. Thanks @rt4914!

2022-10-28 11:33 UTC, Ridhwana approved these changes

2022-10-29 18:28 UTC, merged