Mobile View: Padding Adjust
forem/forem pull request #19061
Opened 2023-02-03 19:11 UTC by lboogie04

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Adjust padding in the mobile view below the icons.
![image](https://user-images.githubusercontent.com/20301788/216686744-df26d67f-f71e-4432-a58d-09b2f0a08ea3.png)

## Related Tickets & Documents
Does not close but addresses the Mobile View fix for Issue [19008](https://github.com/forem/forem/issues/19008)

- Related Issue #19008 
- Closes #

## QA Instructions, Screenshots, Recordings
<img width="381" alt="Screenshot 2023-02-03 at 1 11 05 PM" src="https://user-images.githubusercontent.com/20301788/216687228-40d53a80-38d4-4c3c-ad68-f0f8b79d8732.png">

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](https://media.giphy.com/media/c38XwwG8ZufqPFZuu1/giphy.gif)

2023-02-06 17:30 UTC, rt4914 requested changes
@lboogie04 

From the added image I was able to understand that following changes were expected in this PR:
- Top-padding for entire button: 8px
- Left-padding for entire button: 8px
- Right-padding for entire button: 8px
- Bottom-padding for entire button: 4px
- Gap/margin between the icon and count should be 4px
- Icon should be 32x32 px
- Text should be of 14 px

Based on these tasks I have found following issues:
1. The icon is not 32x32px instead its 24x24px
<img width="352" alt="Screenshot 2023-02-06 at 10 44 26 PM" src="https://user-images.githubusercontent.com/9396084/217039998-0d2f439a-a874-4866-88ae-a638f6128ac6.png">
2. I think bottom padding for entire button is missing. Below are the calculations w.r.t height


- Currently, the entire button height is **58.09px**  (Image-1 attached below)
- Icon's height with padding is **35.98px** (Breakdown of this is: approx 24px icon height, 8px top padding, 4px bottom padding ~= 36px) (Image-2 attached below)
- Text height is **21px** (Image-3 attached below)
- Border top + bottom when icon is highlighted is ~= **1.11px** (Image-4 attached below)
- Total height (58.09px) = icon height + text height + borders = 35.98 + 21 + 1.11 = 58.09px
This calculations assures that the bottom margin of **4px** for entire button is missing.

| Name  | Image |
| ------------- | ------------- |
| Image 1 | <img width="344" alt="Screenshot 2023-02-06 at 10 44 11 PM" src="https://user-images.githubusercontent.com/9396084/217042201-8f713575-d85c-4d8a-aab7-3a23fd631d42.png"> |
| Image 2 | <img width="356" alt="Screenshot 2023-02-06 at 10 44 20 PM" src="https://user-images.githubusercontent.com/9396084/217042344-31e750f1-3b2e-49e2-9956-cfda157c968e.png"> |
| Image 3 | <img width="350" alt="Screenshot 2023-02-06 at 10 44 34 PM" src="https://user-images.githubusercontent.com/9396084/217042419-4e5f5bc2-e556-426d-ac67-6312cdb502d6.png"> |
| Image 4 | <img width="281" alt="Screenshot 2023-02-06 at 10 46 14 PM" src="https://user-images.githubusercontent.com/9396084/217042474-b82a424c-e74a-4479-b546-5408c7c2dcef.png"> |

2023-02-09 09:18 UTC, rt4914 requested changes
Left some comments.

2023-02-09 09:18 UTC, rt4914 commented on app/assets/stylesheets/views/article.scss
> +  padding: 8px 8px 4px 8px;
This changes view for web too. 

### Result from this PR
<img width="451" alt="Screenshot 2023-02-09 at 2 36 49 PM" src="https://user-images.githubusercontent.com/9396084/217768784-0c1c5fd6-bde8-4b3d-8800-f5e601c3fbe4.png">


### Result from Forem.team
<img width="343" alt="Screenshot 2023-02-09 at 2 44 10 PM" src="https://user-images.githubusercontent.com/9396084/217768840-3afcb37c-1c16-4597-afdd-1c145388380a.png">

2023-02-09 09:18 UTC, rt4914 commented on app/helpers/crayons_helper.rb
> +    opts[:height] ||= 32
This is global setting and gets applied to all the crayons icon on the web, as a result we see following changes

### Result on this branch
<img width="385" alt="Screenshot 2023-02-09 at 2 36 00 PM" src="https://user-images.githubusercontent.com/9396084/217769641-ce5d9863-7d15-47d4-b675-7cbff4453035.png">

### Result on dev.to
<img width="270" alt="Screenshot 2023-02-09 at 2 36 11 PM" src="https://user-images.githubusercontent.com/9396084/217769588-c9ae772e-a21c-48fa-8bdf-b57d3a3de672.png">

2023-02-09 09:26 UTC, rt4914 commented on app/helpers/crayons_helper.rb
> +    opts[:height] ||= 32
In `app/views/articles/_multireaction_button.html.erb` we make following change
Before: `<%= image_tag image_active_path, aria_hidden: true, height: 24, width: 24 %>`
After: `<%= image_tag image_active_path, aria_hidden: true, height: 32, width: 32 %>`

This should fix the icon size.

2023-02-10 16:41 UTC, jaw6 approved these changes
Looks okay to me, but would appreciate if @anujbhavsar96 can confirm

2023-02-10 17:13 UTC, rt4914 requested changes
I think it still needs some changes.

[Working Code](https://gist.github.com/rt4914/d784e829ef56c993c5d0ef4c7ad456b1)

### Mocks Screenshot
<img width="632" alt="Screenshot 2023-02-10 at 10 27 08 PM" src="https://user-images.githubusercontent.com/9396084/218151716-a4f6d6e4-00be-4302-8249-bdfe3241cf42.png">

<img width="436" alt="Screenshot 2023-02-10 at 10 50 13 PM" src="https://user-images.githubusercontent.com/9396084/218155559-2da7a391-a42a-4889-9c5a-fc4adb9e746f.png">


In this we can see that the approx size of the entire drawer is **312x93px**. I know we cannot make these exact size UI but still it can give us some idea.

### Output of this PR
|   |  |
| ------------- | ------------- |
| <img width="575" alt="Screenshot 2023-02-10 at 10 23 31 PM" src="https://user-images.githubusercontent.com/9396084/218152959-6c3a31ae-b15c-4c8e-b0a8-f1a9d5fddcc7.png">  | <img width="478" alt="Screenshot 2023-02-10 at 10 26 13 PM" src="https://user-images.githubusercontent.com/9396084/218152969-9bf905e8-329b-483e-86b1-8244345b5c60.png">  |

This width and height for this PR is **394 x 105 px**


### Output of the attached code



|   |  |
| ------------- | ------------- |
| <img width="400" alt="Screenshot 2023-02-10 at 10 24 37 PM" src="https://user-images.githubusercontent.com/9396084/218153440-7ba5c14a-0fec-43ea-966e-4bda63cffacc.png"> | <img width="384" alt="Screenshot 2023-02-10 at 10 25 07 PM" src="https://user-images.githubusercontent.com/9396084/218153452-6d0dcaca-5e41-47c4-af58-09997c8044b6.png"> |


This width and height for the attached PR is **312 x 95 px** [Working Code](https://gist.github.com/rt4914/d784e829ef56c993c5d0ef4c7ad456b1)

2023-02-10 18:02 UTC, merged