Routine rubocop fix
forem/forem pull request #19217
Opened 2023-03-10 18:14 UTC by maestromac

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2023-03-15 08:51 UTC, jaw6 requested changes
So, I'm not really a fan of the config in rubocop that insists on `positive?`, but the changes I'm suggesting here will get this passing CI. However, if our rubocop is configured to autocorrect this way, it's actively going the wrong direction in `spec` and we should actively exclude that cop in `spec`.

2023-03-15 08:51 UTC, jaw6 commented on spec/services/articles/feeds/large_forem_experimental_spec.rb
> +          expect(stories.size).to be.positive?
```suggestion
          expect(stories.size).to be_positive
```

2023-03-15 08:51 UTC, jaw6 commented on spec/services/articles/feeds/article_score_calculator_for_user_spec.rb
> +        expect(applicator.score_comments(article_with_one_comment)).to be.positive?
```suggestion
        expect(applicator.score_comments(article_with_one_comment)).to be_positive
```

2023-03-15 08:51 UTC, jaw6 commented on spec/models/async_info_spec.rb
> +      expect(policies.length).to be.positive?
```suggestion
      expect(policies.length).to be_positive
```

2023-03-15 08:51 UTC, jaw6 commented on spec/workers/follows/update_points_worker_spec.rb
> +      expect(follow.implicit_points).to be.positive?
```suggestion
      expect(follow.implicit_points).to be_positive
```

2023-03-20 21:11 UTC, maestromac commented
@jaw6 Thanks for that suggested fix. I have no idea what I did prior but after rerunning `rubocop -A` again it did not try to try to `.positive?` on those specs.

2023-03-21 13:43 UTC, jaw6 approved these changes
Somehow, the diff became confusing to read here on GitHub.com, but I pulled the branch locally and it looks fine :+1:

2023-03-21 13:55 UTC, merged