Add Uffizzi acknowledgement
forem/forem pull request #19301
Opened 2023-04-06 16:20 UTC by gadkins

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## Description 

Hi! Uffizzi has now provided 250 ephemeral environments (and counting) for the forem project! This PR adds an acknowledgment in the README 😃. (Disclaimer: I work on the Uffizzi project)

## Related Tickets & Documents

- Related Issue # N/A
- Closes # N/A

## QA Instructions, Screenshots, Recordings

N/A

### UI accessibility concerns?

None

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why:  Simple README change
- [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

No

2023-04-06 16:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/forem/forem?pullRequest=19301) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/forem/forem?pullRequest=19301) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/forem/forem?pullRequest=19301) it.</sub>

2023-04-06 17:06 UTC, benhalpern approved these changes
This seems reasonable to me

2023-04-06 18:22 UTC, rt4914 requested changes
@gadkins 
Thanks for the PR. Can you sign the CLA, once that gets signed we can merge this PR - https://github.com/forem/forem/pull/19301#issuecomment-1499319285

2023-04-07 03:20 UTC, gadkins commented
Great! CLA is signed

2023-04-07 15:03 UTC, rt4914 approved these changes

2023-04-07 15:03 UTC, merged