Skip reaction notifications for bookmarks
forem/forem pull request #19426
Opened 2023-05-04 11:19 UTC by filleduchaos

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

We only really intend to send notifications for proper reactions (fire, unicorn, etc), but since bookmarks are internally modelled as reactions they have been inadvertently triggering reaction notifications as well. This PR introduces a `notifiable` list of `ReactionCategory`s so that we can control which reactions or reaction-like things cause a notification to be sent out.

## Related Tickets & Documents

- Related Issue #19356 

## QA Instructions, Screenshots, Recordings

[TODO]

### UI accessibility concerns?

N/A

## Added/updated tests?

- [x] Yes, updated the reaction handler specs
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

Nope

2023-05-05 17:42 UTC, mirie commented
Flagging @pkfrank since I put [Save (bookmark) does not create proper notification](https://github.com/forem/forem/issues/19356) in `blocked` and `needs product` status. Do we want to send notification when a user bookmarks an author's article?

2023-05-08 20:46 UTC, maestromac commented
Marking this as draft for product discussion.

2023-05-22 10:54 UTC, filleduchaos commented
Sorry - please note updated PR description, the product work has been moved to a separate issue so this is now just a bug fix :)

2023-05-23 13:59 UTC, jaw6 requested changes

2023-05-23 13:59 UTC, jaw6 commented on app/services/reaction_handler.rb
> +    return unless ReactionCategory.notifiable.include?(reaction.category.to_sym)
This is reaching into two dependencies in a relatively deep way — and twice in this class. What about adding some method like `Reaction#should_notify?` that encapsulates the logic?

2023-05-26 08:24 UTC, jaw6 approved these changes
:+1:

2023-05-26 08:24 UTC, jaw6 commented on app/models/reaction.rb
>    def skip_notification_for?(_receiver)
At some point in the future, we ought to refactor this method: `_receiver` is required but isn't used, which also makes the method name and explanatory comment a bit misleading.

2023-05-30 23:11 UTC, maestromac approved these changes
LGTM!

2023-05-30 23:12 UTC, merged