Organization Search Filtering
forem/forem pull request #19430
Opened 2023-05-04 17:41 UTC by lboogie04

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

- Related Issue #
- Closes #19364 

## QA Instructions, Screenshots, Recordings

1. Find and/or create 3 organizations via rails console with various names with multiple words.
2. In the search box, input a word from one of the organizations. 
3. Upon being redirected to the search results, you should see the "Organization" tab on the left that can be clicked. 
4. You should see the organization in the list to the right.

<img width="1313" alt="Screenshot 2023-05-05 at 3 04 35 PM" src="https://user-images.githubusercontent.com/20301788/236558551-5571cddc-6dd3-4dd8-99dd-680f1522839d.png">

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [x ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2023-05-05 19:13 UTC, benhalpern commented on app/assets/javascripts/utilities/buildArticleHTML.js
> +            <p>@${article.twitter_username}</p>
This should be their on-site username (i.e. slug for organizations), rather than Twitter username.

2023-05-05 19:14 UTC, benhalpern commented on app/assets/javascripts/utilities/buildArticleHTML.js
> +            <br/>
I think we should do away with this `<br/>` tag and instead do a margin utility class on the below div.

2023-05-05 19:16 UTC, benhalpern requested changes
Looks pretty good overall, made a couple small requests in the rendered html.

I'll note overall that this proliferates some inconsistencies across the frontend here that we should note to circle back and clean up, but having this shipped will be a great forcing function for getting that right — so I'd say we shouldn't shoot to resolve too much of that, or too much pixel-perfection in this pass. I think this is a nice overall implementation.

2023-05-08 12:12 UTC, filleduchaos approved these changes
A couple of quibbles but mostly LGTM!

2023-05-08 12:12 UTC, filleduchaos commented on app/assets/stylesheets/base/helpers.scss
> +  margin-top: var(--su-4);
I think there might be existing utility classes for things like margins and text colour? Although I am still not really sure what approach we're supposed to be taking between Crayons/Tailwind/custom css

2023-05-08 12:12 UTC, filleduchaos commented on app/models/organization.rb
> +  pg_search_scope :search_organizations, against: :name
Would it be useful to search against the slug as well? That would match the search behaviour for users

2023-05-08 13:23 UTC, benhalpern approved these changes

2023-05-08 19:58 UTC, merged