Update multiple_reactions_engagement's alignment
forem/forem pull request #19484
Opened 2023-05-18 13:01 UTC by Kireeti-28

## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

Resolves https://github.com/forem/forem/issues/19474

## QA Instructions, Screenshots, Recordings

- Issue: On iPhone 8, seems like emojis were not aligned with the numbers next to them and was overlapping on text below them.
_![image](https://github.com/forem/forem/assets/97286047/1ec73a3e-f519-4c9c-b1bf-90510b1cb504)_

- Resolution: Made use of flex-box to show the emojis + number combination on UI which eliminates unwanted split between emojis followed by its number.
_![image](https://github.com/forem/forem/assets/97286047/1973c939-747c-4b77-8dba-b7ee12538eb7) _

### UI accessibility concerns?

- Just made use of flex-box which I felt to be an ideal solution for the misalignment issue here.
- From accessibility standpoint, I tested this in smallest screen possible and it worked just fine without any overlapping.
![image](https://github.com/forem/forem/assets/97286047/6eee18b9-1f5e-4fd2-80db-3dc920448d76)

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2023-05-18 13:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/forem/forem?pullRequest=19484) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/forem/forem?pullRequest=19484) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/forem/forem?pullRequest=19484) it.</sub>

2023-05-22 08:52 UTC, Ridhwana commented
HI @Kireeti-28 thank you for submitting this PR. I'm looping in our designer @anujbhavsar96 to give this a look.

2023-05-22 09:59 UTC, anujbhavsar96 approved these changes
This looks great @Kireeti-28 🚀 Thank you for this.

2023-05-22 10:42 UTC, filleduchaos requested changes
Checked it out locally and while the layout is consistent on desktop and mobile 🎉 However, this change causes reactions with zero counts to show up as well (see before/after comparison below)

![Reactions list before](https://github.com/forem/forem/assets/29291843/35e06ac6-1d67-4da0-a5ea-b5c8d8e711be)
![Reactions list after](https://github.com/forem/forem/assets/29291843/0168efc8-6010-4ff4-83c0-b314047722b7)

2023-05-22 12:02 UTC, Kireeti-28 commented on app/assets/stylesheets/views/article.scss
> +   & > span {
Corrected both the code indentation plus showing up reactions with zero count via commit: https://github.com/forem/forem/pull/19484/commits/8508820c2da627ad398e3911047dc8dd0a2226e6

![image](https://github.com/forem/forem/assets/97286047/35231cdb-eae9-4c4c-8800-d605094541a1)


Apologies for not having closer look at first place.

2023-05-23 14:10 UTC, filleduchaos approved these changes
🎉 Excellent!

2023-05-23 14:10 UTC, filleduchaos commented on app/views/articles/_multiple_engagements.html.erb
> +  <% end %>
Oops I forgot to mention that you can take these out, since they will never be rendered

2023-05-31 21:42 UTC, merged