add draft for a value_object to represent search_controller/feed_cont…
forem/forem pull request #19508
Opened 2023-05-19 14:32 UTC by carlosdanielpohlod

…ent params

## What type of PR is this? (check all applicable)

- [ x ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Add value object on search_controller#feed_content to decrease controller responsibilities and give more descriptive names for each conditional statement. Also, one of the conditional statements was removed due is unnecessary.

## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2023-05-19 14:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/forem/forem?pullRequest=19508) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/forem/forem?pullRequest=19508) before we can accept your contribution.<br/><hr/>**Carlos Daniel Pohlod** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/forem/forem?pullRequest=19508) it.</sub>

2023-05-31 21:57 UTC, maestromac commented
Hey @carlosdanielpohlod, how is it going with this PR? how can we help?

2023-06-01 14:17 UTC, carlosdanielpohlod commented
hey @maestromac , I will reopen this pull request. Maybe you saw other pull requests by @gabrielcicero45  with similar changes. This happened because I was helping him to contribute to this project and we have a small confusion during the pull request, so we will close other pull requests and we will consider just this one, thanks for your comprehension

2023-06-06 20:52 UTC, mirie commented
@carlosdanielpohlod Thank you for your contribution! It looks like we have a pending CLA for you. Do you mind signing it? Thanks!

2023-06-08 17:21 UTC, lboogie-ftf commented
@carlosdanielpohlod This is a nice refactor! Thanks for this contribution. Upon signing the pending CLA, I'll return and add my insights/approval.

2023-06-12 14:21 UTC, carlosdanielpohlod commented
@lboogie-ftf @mirie CLI signed!

2023-06-23 13:49 UTC, maestromac requested changes

2023-06-23 13:49 UTC, maestromac commented on app/value_objects/search_resources/feed_content.rb
> +module SearchResources
I see that you are introducing a new "value_object" pattern to our codebase. This is something that would need our eng team's discussion and buy-in. For this moment, can you please move this content to our `app/services/search` folder? thank you.

2023-06-29 16:40 UTC, mirie commented
Hi @carlosdanielpohlod please let us know if you have any questions regarding the changes requested. Thanks again for moving this contribution forward!!

2023-07-06 20:08 UTC, gabrielcicero45 commented
@maestromac  I've made the changes you requested. Whenever you have a moment, please take a look.

2023-07-11 20:11 UTC, rt4914 commented
@maestromac Please have a look at previous comments and the latest changes by author. Thank you.

2023-07-20 15:05 UTC, maestromac requested changes
Thanks again for this PR. Upon closer look, I'm going to have to reject this PR at this state. 

There is value in `value_object` but I don't think refactor is an improvement. The class `Search::FeedContent` exist only to answer `is_homepage_search`, which in this case I would argue would've been better to remain in its current location. I think that it's the wrong focus on what should be refactored. My suggestion for bigger improvement would be to extract the entirety of `#feedcontent`. Follow the [Tell, don't ask](https://thoughtbot.com/blog/tell-dont-ask) principle to refactor out long `if` chains.

You are welcome to continue on this PR or start fresh in a new one.

2023-07-27 21:18 UTC, mirie commented
Hello @carlosdanielpohlod Thank you again for your contribution! I'm going to close this PR for now per the last comment. You're welcome to pick this up again in the future~!

2023-07-27 21:18 UTC, closed without merging