Added limited role
forem/forem pull request #19969
Opened 2023-08-21 18:49 UTC by rt4914

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2023-08-23 08:17 UTC, Ridhwana commented
@rt4914 Just a headsup that I'll look through this PR later today.

2023-08-24 08:11 UTC, Ridhwana requested changes
@rt4914 this looks mostly good, however I think we can rollback that migration.

2023-08-24 13:20 UTC, Ridhwana commented on db/schema.rb
> +ActiveRecord::Schema[7.0].define(version: 2023_08_21_183447) do
@rt4914 are we able to revert the timestamp as well?

2023-08-24 13:31 UTC, rt4914 commented on db/migrate/20230821183447_add_limited_role_to_roles.rb
> +end
Done. Reverted this change

2023-08-24 13:33 UTC, rt4914 commented on db/schema.rb
> +ActiveRecord::Schema[7.0].define(version: 2023_08_21_183447) do
Somehow this got reverted locally. Updated now.

2023-08-24 13:40 UTC, Ridhwana approved these changes
Thanks for those changes @rt4914, this LGTM 🚀

2023-08-25 03:02 UTC, maestromac approved these changes
LGTM!

2023-08-25 09:11 UTC, merged