Remove dead code associated with old roles
forem/forem pull request #20175
Opened 2023-09-28 00:31 UTC by benhalpern

## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Old code related to roles that don't do anything.

2023-09-28 12:31 UTC, lightalloy requested changes
It feels good to remove unused stuff :scissors: 
Let's remove all references of `workshop_pass` and `mod_relations_admin`, I have described in the comments.
You can find them just by searching for `workshop_pass`, `mod_relations_admin`, `workshop_eligible` in the codebase.

2023-09-28 12:31 UTC, lightalloy commented on app/models/role.rb
> -    workshop_pass
Also locales, `role_spec`, and `seeds.rb`

2023-09-28 12:31 UTC, lightalloy commented on app/policies/authorizer.rb
> -    def workshop_eligible?
There is a test in `models/user_spec.rb` which expects this method, let's delete the test.

2023-09-28 19:42 UTC, benhalpern commented
Thanks for the input @lightalloy

2023-09-29 17:22 UTC, lightalloy approved these changes
Thanks for implementing changes, I have removed the related locales as well.

2023-10-01 02:33 UTC, merged