feat: add information about message that appears when scheduling posts
forem/forem pull request #20258
Opened 2023-10-18 22:57 UTC by CBID2

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [X] Documentation Update

## Description
This PR adds a note next to the information about the `published` variable in the Editor Guide. I noticed that when scheduling a post to be published the next day, the message, "This URL is public but secret, so share at your own discretion". After raising this issue to @michael-tharrington and learning that  posts will only appear in feeds and on a user's profile when they are published on the day they are scheduled, we agreed to add this information so that users would gain a better understanding of why this message appears.   
## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [X] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2023-10-18 22:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/forem/forem?pullRequest=20258) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/forem/forem?pullRequest=20258) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/forem/forem?pullRequest=20258) it.</sub>

2023-10-19 18:26 UTC, michael-tharrington requested changes
I think this is right, though I asked @CBID2 (Chrissy) to add a period. And also, is there any way I can see what this message is going to look like once it appears on DEV?

2023-10-19 18:26 UTC, michael-tharrington commented on app/views/pages/_v1_editor_guide_preamble.en.html.erb
Heyo! We need to add a period after "when it's published" so it will appear as "when it's published."

Also, is there any way I can review what this looks like?

2023-10-20 15:38 UTC, lightalloy commented on app/views/pages/_v1_editor_guide_preamble.en.html.erb
@michael-tharrington you can look at the page at [uffizzy](https://pr-20258-deployment-38927-forem.app.uffizzi.com/p/editor_guide)

2023-10-20 20:20 UTC, michael-tharrington commented on app/views/pages/_v1_editor_guide_preamble.en.html.erb
Awesome! Thanks @lightalloy that's super helpful.

2023-10-20 20:22 UTC, michael-tharrington commented
@CBID2, I know we chatted about this a good bit over Discord, but here's what I'm thinking, let's make this change to the **Things to Know** section instead.

![Screen Shot 2023-10-20 at 4 04 48 PM](https://github.com/forem/forem/assets/16007075/59054313-3d04-4d24-a54d-38361a99b266)

And actually, we have the opportunity to make 2 changes!

Here's what I'm thinking (changes in **bold**):
> - We use a markdown editor that uses Jekyll front matter.
> - Most of the time, you can write inline HTML directly into your posts.
> - We support native Liquid tags and created some fun custom ones, too! Trying embedding a Tweet or GitHub issue in your post, using the complete URL: {% embed https://... %}.
> - **Links to unpublished posts (drafts or scheduled posts) are shareable for feedback/review. These posts have a notice which reads "This URL is public but secret, so share at your own discretion." They are not visible in feeds or on your profile until published.**
> - ** When you're ready to publish, set the published variable to true or click publish depending on the editor version, you're using.**

2023-10-20 20:32 UTC, CBID2 commented
Hi @lightalloy! :) The updates have been made, and now my PR is ready to be merged! :)

2023-10-24 18:19 UTC, benhalpern approved these changes
Looks good to me, thanks for the contribution @CBID2!

@michael-tharrington we can verify this in production via the Uffizzi link in the PR — will show us just what it looks like.

2023-10-24 18:19 UTC, merged

2023-10-24 18:26 UTC, CBID2 commented
Woohoo! 😊 Thanks @benhalpern

2023-10-24 18:32 UTC, michael-tharrington commented
Nice @benhalpern! Thanks for merging. 

I think I just need a little demo on where to go to see the Uffizzi link. But I trust this is in good shape. @CBID2 talked about the plans for this one at length in Discord... btw, nice work Chrissy! 🙌