Prevent organizations being created with just integers in their slug
forem/forem pull request #20265
Opened 2023-10-20 13:59 UTC by danielmbrasil

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Add a validation to check if the slug/username contains at least one non-digit character. Add translations for the error message and tests.

## Related Tickets & Documents

- Related Issue #20264
- Closes #20264

## QA Instructions, Screenshots, Recordings

1. Try to create an organization with a slug containing only digits
2. Get an error message telling organizations' slugs must contain at least one non-digit character

No changes to the UI but here's a screenshot with the error message:
![Screenshot from 2023-10-20 10-49-03](https://github.com/forem/forem/assets/51726526/4123a8f6-0f40-4649-94be-1132533dbd7f)

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?
- [X] Yes

2023-10-20 16:03 UTC, danielmbrasil commented on config/locales/models/fr.yml
> +      slug_format: doit inclure au moins un caractère non numérique. Veuillez ajouter d'autres caractères au nom d'utilisateur de votre organisation
I used a translator for this so I'm not sure if this is an accurate translation 😅.

2023-10-20 16:08 UTC, danielmbrasil commented
The last commit should fix the failed CI checks related to RSpec. However, the Crypress checks were also failing and I think it's unrelated. I have another open PR with similar fails. Am I missing something to get the Crypress CI passing?

2023-10-24 10:21 UTC, lightalloy requested changes
Thanks for the pr @danielmbrasil :raised_hands: 

Currently we have slug validations in `CrossModelSlugValidator` (and it already has format validation, but w/o restricting number-only slugs), so it would make sense to validate slug there.

Ideally, we should validate the same way for users, podcast episodes, etc, as mentioned in #19758

As I see, currently we only plan to validate orgs, but it still makes sense to keep slug validations in one place.

Also, there are organizations that have number-only slugs which should be updated before deploying the changes. It was supposed to be done manually by @benhalpern

2023-10-24 12:45 UTC, danielmbrasil commented
Hey @lightalloy,

I've moved the validation to `CrossModelSlugValidator`. However,

> As I see, currently we only plan to validate orgs, but it still makes sense to keep slug validations in one place.

my latest change (be4f9e1c494e152472714028ea9fff973bf73e3b) should affect the slug format validations for the other models too. Should I use a second regex and validate for organizations only as a special case?

2023-10-24 19:44 UTC, benhalpern commented
@lightalloy support task has been completed

2023-10-25 11:04 UTC, lightalloy commented
@danielmbrasil yeah, we need a separate regex for organizations. 
We can't update the regex for other models (like users) at the moment because there are records with number-only slugs in the corresponding tables.

Let's check organizations with a separate regexp. That won't be super "beautiful", but I would accept that trade-off for now.

2023-10-25 13:06 UTC, danielmbrasil commented
@lightalloy I just updated the PR to include the requested changes!

2023-10-25 19:01 UTC, benhalpern approved these changes
Looks good to me, but would love a final @lightalloy check

2023-10-26 11:11 UTC, lightalloy approved these changes
Looks good to me :raised_hands:

2023-10-26 17:08 UTC, merged