Edit comment date to local users date
forem/forem pull request #9569
Opened 2020-07-30 02:11 UTC by eclectic-coding

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
I tested this change by changing me system date from UTC -4 to UTC +2 and created a post and comment in the local environment. Then I changed my system time back. After this fix, the dates display properly. This change implements the new `local_date` helper. 

## Related Tickets & Documents
Fix for #7561 

## QA Instructions, Screenshots, Recordings
![Screenshot from 2020-07-29 22-00-37](https://user-images.githubusercontent.com/13651291/88872151-907d4200-d1e7-11ea-9490-ca351349a650.png)

Hovering over the comment date, should display a formatted date that builds on the displayed short date for the comment.

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## What gif best describes this PR or how it makes you feel?

![alt_text](https://media.giphy.com/media/XbxZ41fWLeRECPsGIJ/giphy.gif)

2020-07-30 02:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/forem/forem?pullRequest=9569) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/forem/forem?pullRequest=9569) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/forem/forem?pullRequest=9569) it.</sub>

2020-07-30 15:21 UTC, eclectic-coding commented
Thanks I will work on this later today.

2021-02-04 15:21 UTC, msarit commented
Hey @eclectic-coding! :wave:
I wanted to check-in and see if you're still working on this PR. Please let us know if you need help, or have any questions. Thanks!

2021-02-04 18:17 UTC, eclectic-coding commented
Yes I will get back into today. I think all that is left is the tests.

2021-03-01 03:12 UTC, citizen428 commented
Hi @eclectic-coding, not meaning to nag, just checking in if there's anything we can do to help you push this over the finish line? Thanks for your efforts so far!

2021-03-01 11:53 UTC, eclectic-coding commented
@citizen428  Sorry for the delay. Just got forem setup on my new hardware and will get into again today. If I need help I will connect back.

2021-03-01 13:05 UTC, eclectic-coding commented
@citizen428 Actually I do need some help. I am not real strong on test and have started this one, but can't figure out how to proceed. If you could give me some input I would appreciate it.

2021-03-02 02:58 UTC, citizen428 commented on .env
> +# Development options
You accidentally commited this file, it shouldn't be here.

2021-03-02 02:58 UTC, citizen428 commented on db/schema.rb
>      t.boolean "export_requested", default: false
This PR has migration, so there shouldn't be any schema changes.

2021-03-02 03:01 UTC, citizen428 commented
@eclectic-coding No worries, You could use [Timecop](https://github.com/travisjeffery/timecop)'s `Timecop.freeze` method to run the assertion at two different times and check that the returned timestamps are what you'd expect.

2021-03-03 01:57 UTC, citizen428 commented on db/schema.rb
> -# This file is auto-generated from the current state of the database. Instead
@eclectic-coding This shouldn't be part of this PR.

2021-03-05 21:17 UTC, maestromac requested changes
Apologies for spotting this just now. Unfortunately, this fix won't work because comments are cached on fastly. This means those dates are UTC, and we provide a raw DateTime for mouse hover. That DateTime is automatically converted by the browser to the user's current timezone.

A solution will have to be javascript on the frontend to convert those displayed times.

2021-03-22 16:53 UTC, msarit commented
@eclectic-coding Hey there! 👋🏾  Thank you for your work on this PR!

There are a few conflicting files to resolve, and Mac suggested [implementing your changes via javascript on the frontend](https://github.com/forem/forem/pull/9569#pullrequestreview-605608466) (since comments are cached).

Let us know if you need any help completing this implementation.

2021-05-03 02:53 UTC, citizen428 commented
Since no work has happened on this PR in almost 2 months I'll close it now. @eclectic-coding Please feel free to reopen it if you pick it up again. Thanks for your contribution!

2021-05-03 02:53 UTC, closed without merging